// ── 11. CROMANCIA — interpretaciones de color ──
window._CROMANCIA_DATA = {
  rojo: {
    energia: "El rojo arde en vos hoy. Es la fuerza de Marte en su expresión más directa: voluntad, impulso, presencia física intensa. Algo en vos necesita actuar, avanzar, ocupar espacio sin pedir permiso. Esta energía no es violencia — es vida en su forma más primitiva y honesta. El rojo es la sangre que corre, el fuego que transforma, la chispa que enciende lo que estaba dormido. Cuando este color te llama, tu cuerpo y tu alma están alineados en una sola dirección: hacia adelante.",
    necesidad: "Tu alma pide movimiento real. No planificación, no análisis — acción concreta y corporal. Necesitás sentirte viva/o a través del cuerpo, de la decisión tomada, del riesgo elegido con conciencia. Hay una energía reprimida que pide salida: puede ser una conversación postergada, un proyecto que empezás hoy, una decisión que ya tomaste internamente pero aún no ejecutaste. Tu necesidad profunda es la de existir plenamente, sin miedo a tomar espacio en el mundo.",
    sombra: "Estás evitando una confrontación necesaria. El rojo que te atrae hoy puede ser la señal de algo que reprimís: una rabia legítima que no te permitiste sentir, un deseo que juzgás como excesivo, una verdad que aún no te animás a decir. La sombra del rojo no es la agresión descontrolada — es la energía que negamos porque nos enseñaron que ocupar espacio es peligroso o egoísta. Lo que ardés hoy, si no lo canalizás conscientemente, puede aparecer como irritabilidad, impaciencia o conflictos inesperados.",
    sombra_rechazada: "Rechazar el rojo hoy sugiere que estás evitando tu propia fuerza. Hay un impulso, una afirmación o una confrontación que sentís como amenazante — para los demás o para la imagen que tenés de vos misma/o. Quizás asociás la intensidad con el peligro, o la fuerza con el daño. Lo que repelés en el rojo es exactamente lo que más necesitás integrar: el derecho a existir con toda tu energía, a querer, a decidir, a ocupar el lugar que te corresponde sin pedir disculpas.",
    planeta: "Planeta: Marte · Chakra: Raíz (Muladhara) — Centro de supervivencia, instinto, vitalidad física y arraigo en la tierra. Cuando Marte activa tu campo energético, el sistema nervioso se prepara para la acción. Es el chakra que conecta tu energía con el mundo material, con tus recursos básicos, con tu sentido de seguridad y pertenencia. La salud de tu raíz determina cuánto te permitís estar completamente presente en tu cuerpo y en tu vida.",
    consejo: "No huyas de tu propio fuego. Lo que ardés hoy no es destructivo — es necesario y sagrado. La diferencia entre el fuego que ilumina y el que consume está en la conciencia con que lo usás. Permití que esa energía se exprese en acción concreta, no en reacción automática. Elegí una cosa — una sola — que hayas postergado por miedo, y hacela hoy. El coraje no es la ausencia de miedo: es el movimiento que das a pesar de él. El fuego que llevás adentro ya sabe el camino."
  },
  naranja: {
    energia: "El naranja que te convoca hoy es la energía del Sol en movimiento combinado con Venus en su aspecto más gozoso. Es la frecuencia de la alegría que busca fluir, de la creatividad que quiere cuerpo y forma. Hay una parte tuya hambrienta de goce genuino, de conexión real, de vitalidad emocional sin filtros ni justificaciones. El naranja es el color del amanecer y del atardecer — los momentos de transición donde la luz se hace más cálida, más humana, más cercana. Tu ser creativo está despierto y reclama expresión.",
    necesidad: "Tu alma pide placer sin culpa y conexión sin agenda. Necesitás darte permiso de disfrutar, de jugar, de crear sin necesitar que sea útil o productivo. Hay una dimensión tuya que lleva demasiado tiempo en modo funcional — resolviendo, produciendo, adaptándose — y hoy pide simplemente existir desde el gozo. La vida tiene sabores que solo se perciben cuando uno para. Tu necesidad más profunda hoy es la de sentirte viva/o de una manera que no requiera justificación.",
    sombra: "Hay una tristeza o una aridez emocional que estás disfrazando de actividad o de búsqueda constante de estímulo. El naranja puede ser la búsqueda compulsiva de conexión para no sentir la soledad que espera debajo. También puede señalar una creatividad bloqueada que se expresa como frustración, envidia de la vida de otros, o una sensación difusa de que algo falta. La sombra del naranja es el placer que se vuelve escapismo, la alegría forzada que tapa el dolor real.",
    sombra_rechazada: "Rechazar el naranja hoy habla de una alegría que te cuesta aceptar — quizás la tuya, quizás la ajena. Algo en vos desconfía del gozo, lo ve frívolo, superficial o incluso peligroso. Puede haber una creencia arraigada de que no merecés disfrutar sin haber trabajado lo suficiente, o que la felicidad es una trampa. O quizás estás en un momento de duelo real y el naranja te resulta demasiado brillante para lo que sentís por dentro.",
    planeta: "Planeta: Sol (energía solar secundaria) / Venus · Chakra: Sacro (Svadhisthana) — Centro de creatividad, sensualidad, placer y flujo emocional. Este chakra gobierna nuestra capacidad de sentir, de movernos con la vida, de aceptar el cambio como parte del ritmo natural. Cuando está activo, hay fluidez, apertura y gozo. Cuando está bloqueado, aparece la rigidez emocional, el miedo al placer y la dificultad para dejar ir.",
    consejo: "Hoy no es día de seriedad excesiva ni de productividad como forma de demostrar tu valor. Encontrá al menos un momento donde existas sin producir ni justificar. Puede ser pequeño: música que te mueva, una conversación real, algo hecho con las manos. La alegría no te resta — te recarga. Y lo que creás desde el gozo tiene una calidad diferente a lo que hacés desde la obligación. Dale permiso hoy a la parte de vos que sabe cómo disfrutar sin pedir disculpas."
  },
  amarillo: {
    energia: "El amarillo vibrante que te atrae hoy es la energía de Mercurio y del Sol en su aspecto más luminoso: claridad mental, comunicación, poder de síntesis y entendimiento profundo. Tu mente está particularmente activa, receptiva y necesita expresarse. Este es el color del intelecto despierto, de la intuición que se vuelve concepto, de la idea que finalmente encuentra palabras. El amarillo es también el color de los nervios y de la red que conecta — hoy estás especialmente sensible a la información, a los mensajes, a las conexiones entre ideas que antes parecían separadas.",
    necesidad: "Tu alma pide claridad y expresión genuina. Hay algo que querés entender, nombrar, articular con precisión. Necesitás organizar lo que pensás — quizás escribir, hablar con alguien de confianza que realmente escuche, o simplemente darle forma verbal a lo que llevas tiempo sintiendo sin poder decirlo. También puede ser que necesités recibir información importante — leer, estudiar, aprender algo nuevo que abra una perspectiva que no tenías. La necesidad de hoy es la del entendimiento como forma de liberación.",
    sombra: "Estás usando la mente para evitar el corazón. El exceso de análisis, de explicaciones, de palabras puede ser una forma sofisticada de no sentir lo que está esperando debajo. La sombra del amarillo es la sobreexplicación que protege de la vulnerabilidad, la racionalización que justifica lo que en realidad es miedo o herida. También puede aparecer como ansiedad mental, pensamientos en loop, o la sensación de que cuanto más pensás menos llegás a algún lugar. La claridad que buscás hoy quizás no sea conceptual sino emocional.",
    sombra_rechazada: "Rechazar el amarillo hoy sugiere que hay algo que no querés ver con demasiada claridad. Una verdad incómoda que preferís dejar borrosa porque nombrarla implicaría tener que actuar en consecuencia. O quizás hay un exceso de información y análisis en tu vida que te agotó y hoy necesitás silencio más que palabras. El rechazo al amarillo puede también hablar de una desconfianza hacia el pensamiento propio — una voz interna que dice que lo que pensás no tiene valor.",
    planeta: "Planeta: Mercurio / Sol · Chakra: Plexo Solar (Manipura) — Centro de voluntad, autoconfianza, identidad y poder personal. También conecta con el Chakra de Garganta (Vishuddha) — la expresión auténtica de lo que pensás y sentís. Mercurio rige los procesos mentales, la comunicación y los vínculos. Cuando está activo y en equilibrio, hay claridad, fluidez verbal y capacidad de conectar ideas con facilidad. Cuando está en tensión, aparece la confusión, el pensamiento obsesivo o la dificultad para decir lo que realmente se piensa.",
    consejo: "La luz que buscás está dentro tuyo — no en otra explicación, otro libro, otra opinión. En vez de buscar respuestas afuera, sentate en silencio y preguntate qué sabés — que ya sabés — pero todavía no te animás a admitir plenamente. Escribí sin censura durante diez minutos: no para que quede bien, sino para descubrir lo que ya está formado en vos. La mente es una herramienta poderosa. Usada con conciencia, puede iluminar lo que el corazón ya sabe y aún no se animó a decir en voz alta."
  },
  verde: {
    energia: "El verde que te llama hoy es la energía de Venus en su aspecto terrenal más profundo: amor que sana, equilibrio que se busca, abundancia que fluye desde la conexión real. Hay una necesidad de armonía que tu sistema entero está procesando — no como estética, sino como necesidad vital. El verde es el color de todo lo que crece, de lo que tiene raíz y sabe hacia dónde ir. Es también la frecuencia del corazón cuando está abierto: generoso, receptivo, capaz de dar y de recibir sin calcular.",
    necesidad: "Tu alma pide amor en su forma más genuina — no necesariamente romántico. Pide ternura, cuidado real, conexión sin máscaras. Necesitás sentirte parte de algo vivo, perteneciente a algo que te contiene, querida/o sin condiciones ni expectativas. Puede ser la necesidad de reconectar con la naturaleza, con tu cuerpo, con alguien con quien podés ser completamente vos misma/o. También puede ser la necesidad de darte a vos misma/o el amor y el cuidado que das tan fácilmente a los demás.",
    sombra: "Estás descuidando tu propio corazón mientras cuidas el de todos los demás. Hay una generosidad que viene del miedo a no ser suficiente o a no ser amada/o, no del amor genuino. O bien hay una situación que requiere perdón — hacia alguien que te lastimó, o hacia vos misma/o por algo que todavía no te perdonaste. La sombra del verde puede aparecer como dependencia emocional, celos, o una necesidad de aprobación que nunca termina de llenarse porque viene del lugar equivocado.",
    sombra_rechazada: "Rechazar el verde hoy puede hablar de un miedo al amor o a la vulnerabilidad que implica abrirse genuinamente. Hay una abertura emocional que sentís como riesgo — y quizás lo fue en el pasado, con razones reales. O puede ser que estés tan en modo supervivencia o producción que el verde te parece un lujo que no podés darte ahora. Lo que repelés es exactamente la medicina: el permiso de recibir, de ser cuidada/o, de no tener que estar siempre fuerte.",
    planeta: "Planeta: Venus · Chakra: Corazón (Anahata) — Centro de amor incondicional, compasión, sanación y conexión profunda. El corazón es el puente entre el mundo físico y el espiritual en la tradición de los chakras. Cuando está abierto, hay flujo, generosidad y paz interior. Cuando está cerrado o herido, aparece el aislamiento, la dureza como protección, o la dependencia emocional como forma de buscar lo que uno no puede darse a sí mismo.",
    consejo: "No hay sanación sin contacto real — con otros, con la naturaleza, con vos misma/o. Permití que algo te llegue hoy sin controlarlo ni analizarlo: una conversación donde escuchés de verdad, un momento en el que el sol te dé en la cara, una expresión de afecto que no necesitás merecer ni devolver de inmediato. El amor no es un recurso escaso que se agota — cuanto más fluye, más se regenera. Hoy practicá recibir con la misma apertura con la que sabés dar."
  },
  azul: {
    energia: "El azul profundo que te atrae hoy es la energía de Neptuno y Júpiter en su frecuencia más elevada: verdad interior, espiritualidad que no necesita adornos, intuición que supera la lógica. Tu alma está en un momento de contemplación activa, de búsqueda de sentido más allá de lo inmediato. El azul es el color del cielo y del mar — los dos grandes espejos que la humanidad ha mirado siempre cuando necesita perspectiva. Hoy algo en vos mira hacia adentro y hacia arriba al mismo tiempo, buscando una comprensión que las palabras ordinarias no alcanzan.",
    necesidad: "Tu alma pide silencio real y profundidad auténtica. Necesitás alejarte del ruido externo — de las opiniones, de las noticias, de las demandas — y escuchar algo que solo se oye en calma. Hay una voz interna — intuición, guía interior, sabiduría acumulada — que espera tu atención y que lleva tiempo hablando en susurros que no has podido escuchar. La necesidad de hoy no es de información sino de contemplación: de estar con lo que es, sin querer cambiarlo ni entenderlo todo.",
    sombra: "Estás usando la espiritualidad, la calma o la elevación como forma de desconectarte del mundo real y de sus demandas. El azul puede ser evasión disfrazada de profundidad — la meditación que evita la conversación difícil, la búsqueda espiritual que posterga la decisión concreta, la elevación que sirve para no ensuciarse las manos con la vida. La sombra del azul también puede aparecer como una tristeza difusa, una melancolía que se instala cuando uno lleva demasiado tiempo en un estado de desconexión de lo mundano.",
    sombra_rechazada: "Rechazar el azul hoy puede revelar una dificultad profunda para confiar — en el proceso de la vida, en algo más grande que la voluntad individual, en el misterio como parte necesaria de la existencia. Hay una fe — no religiosa necesariamente, sino básica, existencial — que todavía no encontrás o que perdiste. El rechazo al azul puede hablar también de un miedo al silencio: de lo que podrías encontrar si te quedás en calma el tiempo suficiente para escuchar lo que ya sabés.",
    planeta: "Planeta: Neptuno / Júpiter · Chakra: Garganta (Vishuddha) y Tercer Ojo (Ajna) — Expresión auténtica de la verdad interior, intuición activa, visión espiritual y acceso a una percepción que supera los cinco sentidos. Neptuno disuelve los límites del ego para permitir la conexión con algo más grande. Júpiter expande la visión y abre la comprensión. Juntos, crean las condiciones para la revelación — esos momentos en que algo se hace claro de una manera que no puede ser completamente explicada.",
    consejo: "La verdad que buscás hoy no está en la mente ni en ninguna explicación exterior. Escuchá más que pensá. Observá más que analizá. Dejate sorprender por lo que ya está presente. La respuesta que necesitás — sobre tu camino, sobre una relación, sobre quién sos — ya está en vos, esperando el espacio de quietud necesario para hacerse audible. Hoy un solo acto de silencio genuino vale más que mil palabras. Confiá en lo que sentís aunque no puedas explicarlo."
  },
  violeta: {
    energia: "El violeta que te atrae hoy es la energía de Saturno y Plutón en su aspecto más transformador y sagrado: la frecuencia de la metamorfosis, del misterio que no puede ser reducido, de la muerte simbólica que precede a todo renacimiento real. Algo en vos está atravesando un proceso profundo — quizás invisible desde afuera, quizás silencioso, pero absolutamente real. El violeta es el color de los umbrales: de los momentos en que uno cruza de un estado de ser a otro y ya no puede volver al anterior. Estás en uno de esos momentos.",
    necesidad: "Tu alma pide transformación real, no cosmética. No un cambio de hábitos superficial sino una revisión profunda de algo que ya cumplió su ciclo. Hay algo — un patrón, una creencia, una relación con vos misma/o o con alguien más — que tu sistema sabe que debe soltar, aunque la mente todavía no quiera reconocerlo completamente. La necesidad de hoy es la de bajar a las raíces, de mirar lo que hay debajo de la superficie, de hacer el trabajo que transforma en vez del que solo mantiene.",
    sombra: "Estás romantizando el sufrimiento o la oscuridad como formas de profundidad. El violeta como compulsión puede hablar de una relación no resuelta con el dolor — usarlo como identidad, como barrera, o como forma de no tener que ser ordinariamente feliz. También puede señalar una fascinación con el poder o el misterio que esconde un miedo al amor simple, a lo cotidiano, a la alegría sin drama. La transformación que buscás puede estar más cerca y más simple de lo que querés creer.",
    sombra_rechazada: "Rechazar el violeta hoy puede ser una resistencia activa a la transformación que ya está ocurriendo de todas formas. Hay algo que cambia en vos — en tu forma de ver, de relacionarte, de entenderte — y una parte de vos prefiere ignorarlo porque cambiar significa soltar algo conocido, aunque ese algo ya no te sirva. El rechazo al violeta también puede hablar de un miedo a la profundidad propia, a lo que podrías encontrar si te mirarás sin los filtros habituales.",
    planeta: "Planeta: Plutón / Saturno · Chakra: Corona (Sahasrara) — Conexión con lo divino, trascendencia, conciencia expandida que supera la identidad individual. También activa el Chakra Raíz en su aspecto más ancestral: los patrones heredados, los mandatos familiares, lo que viene de más atrás que tu propia historia. Plutón rige las transformaciones inevitables, las crisis que abren paso a algo nuevo, la muerte y el renacimiento en todos sus niveles. Saturno pone la estructura y la seriedad necesaria para que la transformación sea real y duradera.",
    consejo: "Confiá en el proceso de lo que no entendés todavía. La oscuridad que sentís hoy no es el final — es el útero de algo que todavía no tiene forma visible. Lo que muere en vos hace espacio exacto para lo que debe nacer. No intentes acelerar la metamorfosis ni volver atrás: ninguna de las dos cosas es posible en este punto. Lo que se te pide hoy es la confianza radical en el proceso, en tu propia capacidad de renacer, y en que lo que perdés en esta transición tenía que soltarse para que puedas ser lo que realmente sos."
  },
  blanco: {
    energia: "El blanco que te atrae hoy es la energía de la Luna y de Neptuno en su aspecto más puro y liminal: la frecuencia de los comienzos, de la pureza de intención que precede a toda acción significativa. Tu sistema energético está pidiendo un reset genuino — no un cambio de decoración sino un regreso a lo esencial, a lo que queda cuando se quitan todas las capas que no son realmente tuyas. El blanco contiene todos los colores y al mismo tiempo no es ninguno en particular: es el espacio de posibilidad pura, anterior a toda elección.",
    necesidad: "Tu alma pide pureza y simpleza radical. Estás sobrecargada/o de capas acumuladas — opiniones ajenas internalizadas como propias, roles que cumplís sin haberlos elegido conscientemente, expectativas de otros que llevas como si fueran tuyas. Necesitás volver a lo más esencial de quién sos cuando no hay nada que demostrar, nadie que impresionar, ningún resultado que producir. La necesidad de hoy es la del espacio vacío como forma de libertad, no como carencia.",
    sombra: "Estás borrando o negando partes de vos misma/o en un intento de parecer más pura/o, más aceptable, más espiritual o más correcta/o. El blanco como compulsión puede ser una forma de huir de la complejidad real de quien sos — de tus contradicciones, tus deseos, tu sombra — eligiendo una versión simplificada que sea más fácil de presentar. La pureza que no integra la sombra no es pureza: es negación. Lo que no reconocés en vos misma/o no desaparece — se vuelve inconsciente y más difícil de manejar.",
    sombra_rechazada: "Rechazar el blanco puede hablar de una dificultad real para comenzar de nuevo — un apego profundo a lo que fue, a una identidad que ya no encaja pero que da miedo soltar porque todavía es conocida. O puede ser un miedo a quedar vacía/o sin las estructuras habituales, sin los roles y las certezas que organizan el sentido de quien uno es. El rechazo también puede señalar que estás en un momento de tanta intensidad que la simpleza del blanco te resulta inalcanzable o incluso ofensiva.",
    planeta: "Planeta: Luna / Neptuno · Chakra: Corona (Sahasrara) — Pureza espiritual, claridad de propósito, conexión con el origen y con lo que está más allá de la personalidad individual. La Luna rige los ciclos, la memoria emocional, el inconsciente y la capacidad de soltar y renovar. Neptuno disuelve lo que ya no es necesario y abre el canal a la inspiración más sutil. Juntos, crean la condición para el verdadero comienzo: el que nace del vaciamiento genuino, no del olvido.",
    consejo: "No necesitás ser perfecta/o, estar lista/o ni haber resuelto todo lo anterior para empezar de nuevo. La pureza que buscás no es la ausencia de sombra — es la presencia honesta y plena ante todo lo que realmente sos: lo luminoso y lo oscuro, lo logrado y lo pendiente, lo que te enorgullece y lo que todavía te cuesta mirar. El espacio en blanco no está vacío — está lleno de posibilidad. Hoy permití que algo nuevo entre, sin saber todavía exactamente qué forma va a tomar."
  },
  negro: {
    energia: "El negro que te atrae hoy es la energía de Saturno y Plutón en su forma más concentrada y esencial: la profundidad de lo que aún no ha tomado forma, la gestación en la oscuridad, el poder silencioso de lo que madura sin necesitar ser visto. El negro no es ausencia — es plenitud de una naturaleza diferente. Es el color del espacio entre las estrellas, del suelo fértil donde germina lo que todavía no existe, del silencio que precede a la palabra que cambia todo. Algo en vos está en proceso de formación, profundo y real, que todavía no está listo para mostrarse.",
    necesidad: "Tu alma pide recogimiento genuino — no aislamiento, no huida, sino la retirada voluntaria del que sabe que necesita silencio para escuchar. Necesitás entrar hacia adentro, procesar en profundidad sin interferencias, dejar que algo madure en vos sin la presión de tener que explicarlo, mostrarlo o producir resultados visibles. Hay una sabiduría que solo emerge en la quietud, un entendimiento que no puede ser apresurado. Tu necesidad hoy es la del útero: oscuro, silencioso, protegido, lleno de vida que aún no tiene nombre.",
    sombra: "Estás usando la introspección, el silencio o la reserva como escudo defensivo. Hay algo que evitás mostrar — quizás una necesidad de ayuda que sentís como debilidad, una emoción vulnerable que expondrías si alguien te viera de verdad, una verdad que requeriría ser vista y acompañada por otros. La sombra del negro puede aparecer como aislamiento que se disfraza de profundidad, como una soledad elegida que en realidad es miedo al rechazo o a la intimidad real.",
    sombra_rechazada: "Rechazar el negro hoy puede hablar de un miedo a la profundidad propia, a la soledad interior, o a lo que podrías encontrar si te quedaras en silencio y quietud el tiempo suficiente. También puede señalar una relación difícil con la oscuridad en cualquiera de sus formas: el inconsciente, los aspectos no integrados de tu personalidad, los duelos no completados, los miedos que prefieren la distracción a ser mirados. Lo que huís en el negro es también lo que más tiene para enseñarte.",
    planeta: "Planeta: Saturno / Plutón · Chakra: Raíz (Muladhara) en su aspecto más profundo y ancestral — la conexión con la tierra, con los ancestros, con el inconsciente colectivo, con todo lo que viene de antes de vos y que vive en vos sin que lo hayas elegido conscientemente. También activa el Chakra Corona en su aspecto más oscuro: la conciencia que trasciende al yo y puede contener el misterio sin necesitar resolverlo.",
    consejo: "Lo que germina en la oscuridad no necesita que lo apresures, que lo ilumines prematuramente ni que lo expliques antes de que esté listo. Tu proceso interno — cualquiera que sea — es tan real y tan valioso como cualquier acción visible. Confiá en lo que todavía no podés ver. Dale al silencio el espacio que merece. Y si hay algo que llevas evitando mirar, considerá que la oscuridad no lo hará desaparecer: solo lo contendrá hasta que estés lista/o para encontrarlo con más recursos de los que tenías antes."
  },
  dorado: {
    energia: "El dorado que te atrae hoy es la energía del Sol en su máxima y más plena expresión: dignidad que no necesita ser demostrada, autoconfianza que nace del conocimiento propio, éxito consciente que viene de la alineación con el propósito, liderazgo que emerge del ser y no de la necesidad de control. Algo en vos está listo para brillar — no para los demás, no como performance — sino porque es su momento natural. El dorado es el color del metal que sobrevivió el fuego y se purificó. Lo que brillas hoy viene de haber pasado por algo.",
    necesidad: "Tu alma pide reconocimiento genuino — pero no el de los demás. El tuyo propio. Necesitás honrar lo que has construido, lo que has atravesado, lo que sos en la actualidad. Hay una grandeza — real, ganada, legítima — que minimizás por hábito, por modestia mal entendida, o por el miedo inconsciente a destacar. La necesidad de hoy es la de pararte frente a vos misma/o y decir: esto que soy tiene valor. Lo que he hecho importa. El lugar que ocupo en el mundo es mío por derecho.",
    sombra: "Hay una arrogancia o una búsqueda compulsiva de validación que se disfraza de autoconfianza — la necesidad de que otros confirmen tu valor porque internamente aún no te lo creés del todo. O lo opuesto: una grandeza real que reprimís sistemáticamente por miedo a las envidias ajenas, por no querer destacar, por no sentirte merecedora/or de ese lugar. La sombra del dorado puede aparecer como narcisismo defensivo, como la necesidad de dominar para compensar la inseguridad, o como el sacrificio de la propia luz para hacer cómodos a los demás.",
    sombra_rechazada: "Rechazar el dorado hoy puede revelar una relación complicada y no resuelta con el éxito, el poder o el brillo personal. Algo en vos siente que no merece ocupar ese lugar luminoso — quizás porque en el pasado cuando brillaste hubo consecuencias difíciles, o porque un mensaje temprano te dijo que sobresalir es peligroso o desleal. El rechazo al dorado también puede hablar de una desidentificación con el éxito como valor, una resistencia a cierta concepción del poder que aún no has podido resignificar desde tus propios valores.",
    planeta: "Planeta: Sol · Chakra: Plexo Solar (Manipura) en su expresión más elevada — voluntad consciente, identidad solar, propósito que se alinea con el bien mayor. El Sol representa el núcleo del ser, aquello que permanece constante debajo de todos los roles y las adaptaciones. Cuando el Plexo Solar está activo y en equilibrio, hay presencia, iniciativa, confianza genuina en los propios recursos y capacidad de actuar desde el centro en vez de desde la periferia del miedo.",
    consejo: "La luz que sos no es vanidad — es servicio. Cuando brillás desde tu verdad más auténtica, le das permiso implícito a otros de hacer lo mismo. Apagar tu luz para que otros se sientan cómodos no es humildad — es una forma de desleal con lo que viniste a ser y a hacer. Hoy reconocé algo que lograste, algo que sos, algo que te costó y que sin embargo alcanzaste. No para presumirlo — sino para honrarlo con la seriedad y el amor que merece. Eso es la dignidad solar."
  },
  plateado: {
    energia: "El plateado que te atrae hoy es la energía lunar en su aspecto más refinado, sutil y misterioso: intuición que supera la lógica, ciclos que tienen su propia sabiduría, reflexión que revela más que la acción directa. Tu mundo interior está particularmente activo — sueños más vívidos, presentimientos que no terminás de ignorar, sincronías que parecen mensajes, una sensación difusa pero persistente de que algo está por cambiar o de que ya cambió sin que te hayas dado cuenta todavía.",
    necesidad: "Tu alma pide tiempo para escuchar su propia luna interna — ese ritmo íntimo que tiene ciclos propios y que no siempre coincide con el calendario exterior. Necesitás tiempo para sentir sin racionalizar inmediatamente, para dejar que la intuición hable antes que la mente *****ítica intervenga con sus interpretaciones. Hay mensajes llegando desde tu mundo interior — desde los sueños, desde las emociones que aparecen sin razón aparente, desde las sensaciones corporales — que merecen tu atención antes de ser descartados.",
    sombra: "Estás oscilando entre estados de ánimo sin ancla, sin hilo conductor que te permita entender el patrón de lo que sentís. La energía lunar sin raíz puede volverse inestabilidad emocional, reactividad, o una sensación de ser arrastrada/o por las emociones en vez de habitarlas conscientemente. También puede aparecer como una espiritualidad escapista: usar la intuición, los sueños o el mundo interior como forma de evitar compromisos concretos y decisiones que requieren presencia en lo mundano.",
    sombra_rechazada: "Rechazar el plateado hoy puede hablar de una desconexión de tu mundo interior, de tus ritmos naturales, de la parte de vos que no siempre tiene explicación racional pero que es absolutamente real. Puede haber un exceso de racionalismo que descarta lo que no puede ser probado, una desconfianza hacia la intuición como fuente válida de conocimiento. O quizás llevas tanto tiempo en modo acción y producción que el mundo interior te resulta ahora casi extraño, como un territorio al que ya no sabés cómo acceder.",
    planeta: "Planeta: Luna · Chakra: Tercer Ojo (Ajna) — Intuición activa, percepción sutil, acceso a la memoria emocional profunda y a la sabiduría que va más allá del pensamiento lineal. También activa el Chakra Sacro (Svadhisthana) en su aspecto más fluido y receptivo. La Luna rige los ciclos, las mareas internas, el inconsciente personal y la capacidad de conectar con los ritmos más profundos de la vida — los que no responden al reloj sino a algo más antiguo.",
    consejo: "No todo lo que sentís necesita ser comprendido para ser válido. No toda percepción necesita ser demostrada para merecer atención. Hoy confiá en lo que percibís aunque no puedas explicarlo con palabras precisas o argumentos sólidos. Tu intuición es un instrumento afinado a lo largo de años de experiencia — usalo con la misma seriedad con que usarías cualquier otra herramienta de conocimiento. Escuchá los sueños de esta noche. Prestá atención a las primeras impresiones. Tomá nota de lo que aparece sin que lo invites."
  }
};