// ── RUNAS — Runa Personal | Runa Anual | Runa de Nacimiento ──────────────────────
// Calculado igual que numerología: por fecha de nacimiento
// Runa Personal: suma total de la fecha, reducir a 1-24
// Runa Anual: suma de día + mes + año actual, reducir a 1-24
// Las imágenes se añadirán cuando estén disponibles

window._RUNAS = {
  1: {
    nombre: 'Fehu', simbolo: 'ᚠ',
    img: 'https://static.wixstatic.com/media/0bac9e_8fb1feacddaa45488809bf4ec576328c~mv2.png',
    // Runa Personal
    desc_personal: 'Tu runa personal es Fehu, y te define como una persona cuya naturaleza más profunda está ligada a la abundancia en movimiento. Tu personalidad no acumula: genera, comparte y hace circular lo que tiene valor. Eres alguien que sabe intuitivamente que la riqueza guardada se pudre y la energía estancada enferma. Tienes una vitalidad que atrae recursos, pero tu verdadero don no está en lo que posees sino en lo que pones en circulación.',
    consejo_personal: 'Fehu gnósticamente representa el fuego primordial de la creación: la chispa que inicia todo ciclo. Tu prosperidad fluye cuando eres canal y no recipiente cerrado.',
    // Runa Anual
    desc_anual: 'En este año, Fehu marca el inicio de un ciclo de abundancia activa. No es un año para guardar ni para esperar: es un año para mover, intercambiar y hacer circular lo que tienes — talentos, recursos, contactos, energía. Lo que pongas en movimiento este año tiene potencial de multiplicarse. Lo que guardes por miedo puede volverse estéril.',
    consejo_anual: 'Este año Fehu te pide que confíes en el flujo. No hoards. Lo que das vuelve multiplicado; lo que retienes se convierte en peso.',
    // Runas de Nacimiento
    desc_dia: 'Fehu en tu día de nacimiento imprime en tu carácter una relación instintiva con la abundancia y el valor. Naciste con un sentido natural del intercambio y una capacidad de generar donde otros solo ven escasez. Este sello del día habla de alguien que llegó al mundo con el fuego del creador encendido.',
    desc_mes: 'La runa del mes en que naciste es Fehu, lo que señala que el ciclo estacional de tu nacimiento estaba marcado por la energía del flujo y la prosperidad circulante. Hay en tu manera de relacionarte con el mundo material una fluidez que viene de este sello: sabes mouverte entre lo que vale y lo que no.',
    desc_anio: 'Tu runa del año de nacimiento es Fehu, lo que imprime en tu generación una misión colectiva ligada a la transformación de los sistemas de valor. Tu año de llegada al mundo vibraba con la frecuencia del intercambio y la riqueza viva. Compartes con quienes nacieron en ese año una comprensión intuitiva de que el valor es energía, no cosa.'
  },
  2: {
    nombre: 'Uruz', simbolo: 'ᚢ',
    img: 'https://static.wixstatic.com/media/0bac9e_45c234edd6d94e069b1a22de9317a1b7~mv2.png',
    desc_personal: 'Tu runa personal es Uruz, y te define como una persona de una fuerza interior que a menudo tú mismo subestimas. Tu personalidad tiene la potencia del uro, la bestia salvaje que no puede ser domesticada del todo: hay en ti una vitalidad, una salud energética y una capacidad de recuperación que sorprenden a quienes te observan de cerca. Eres más resistente de lo que crees y más poderoso de lo que te permites mostrar.',
    consejo_personal: 'Uruz gnósticamente es la fuerza bruta del universo antes de tomar forma. Cuando te conectas con esa energía primaria desde la consciencia, eres capaz de transformaciones que otros considerarían imposibles.',
    desc_anual: 'En este año, Uruz trae consigo una renovación de fuerzas. Es un año para reconectar con tu vitalidad más básica, para sanar el cuerpo si lo has descuidado y para redescubrir de qué eres capaz cuando no te pones límites internos. Algo en ti quiere recuperar su fuerza original este año. Permítelo.',
    consejo_anual: 'Uruz en año personal te pide que no desperdicies tu energía en lo que no importa. Identifica dónde va tu fuerza y redirígela hacia lo que realmente construyes.',
    desc_dia: 'Uruz en tu día de nacimiento sella tu carácter con una vitalidad instintiva y una fuerza física y anímica que te acompañará toda la vida. Naciste con la energía del uro en tu centro: no es agresividad, es potencia. La manera en que te mueves por el mundo tiene algo de indomable que los demás perciben aunque no sepan nombrarlo.',
    desc_mes: 'La runa del mes en que naciste es Uruz, marcando ese ciclo estacional con la energía de la salud, la fuerza y la renovación. Hay en tu constitución energética una capacidad de regeneración que viene de este sello mensual: cuando caes, te levantas con más fuerza de la que tenías antes.',
    desc_anio: 'Tu runa del año de nacimiento es Uruz, lo que habla de una generación que vino al mundo con una misión de restaurar lo auténtico y lo vital. Tu año de llegada vibraba con la frecuencia de la fuerza primaria. Los de tu generación comparten una resistencia y una energía de renovación que se activa especialmente en tiempos de crisis.'
  },
  3: {
    nombre: 'Thurisaz', simbolo: 'ᚦ',
    img: 'https://static.wixstatic.com/media/0bac9e_e13683b2c8bb4579a2343fede93e28ad~mv2.png',
    desc_personal: 'Tu runa personal es Thurisaz, y te define como alguien que camina con un poder que puede destruir o proteger según cómo lo usa. Tu personalidad tiene una fuerza que incomoda a quienes prefieren la comodidad y el consenso: eres el espino que marca el límite, la tormenta que limpia el aire antes del sol. No eres fácil, pero eres necesario. La intensidad de tu presencia no es un defecto sino una función.',
    consejo_personal: 'Thurisaz gnósticamente es la puerta al caos creador, la fuerza que derrumba las estructuras falsas para que emerja la verdad. Respeta tu propio poder y no lo uses sin intención.',
    desc_anual: 'En este año, Thurisaz anuncia cambios que llegan con fuerza. No son cambios graduales ni suaves: son rupturas necesarias, puertas que se cierran de golpe para que otras se abran. Este año exige que te relaciones diferente con el poder — el tuyo y el de las circunstancias. No resistas lo que tiene que cambiar; canaliza la energía de la ruptura hacia la creación.',
    consejo_anual: 'Thurisaz en año personal avisa: habrá tormenta, pero la tormenta tiene un propósito. Lo que se rompe este año ya estaba roto; solo se vuelve visible.',
    desc_dia: 'Thurisaz en tu día de nacimiento marca tu carácter con una intensidad que puede ser difícil de contener pero imposible de ignorar. Naciste con la fuerza del gigante y el filo del espino: una presencia que no pasa desapercibida, una energía que puede transformar lo que toca. Aprender a usar ese poder con consciencia es el trabajo de toda una vida.',
    desc_mes: 'La runa del mes en que naciste es Thurisaz, lo que señala que llegaste en un tiempo de transición y fuerza transformadora. Hay en tu manera de enfrentar los obstáculos algo de inevitabilidad: cuando algo tiene que cambiar en tu entorno, sueles ser tú quien cataliza ese cambio aunque no lo hayas buscado.',
    desc_anio: 'Tu runa del año de nacimiento es Thurisaz, hablando de una generación que llegó al mundo en un tiempo de rupturas y transformaciones profundas. Tu año de llegada vibraba con la frecuencia del cambio disruptivo. Los de tu generación son catalizadores innatos: donde llegan, algo se mueve aunque nadie se lo pida.'
  },
  4: {
    nombre: 'Ansuz', simbolo: 'ᚨ',
    img: 'https://static.wixstatic.com/media/0bac9e_eb097e5ea6ec47f5ac793cc78dfb5bdc~mv2.png',
    desc_personal: 'Tu runa personal es Ansuz, y te define como una persona cuya naturaleza más profunda es la de un canal entre lo visible y lo que está más allá. Tu personalidad tiene algo del mensajero: captas lo que otros no escuchan, recibes inspiraciones que llegan sin aviso y tienes una facilidad con las palabras y la comunicación que puede ser tanto un don como una responsabilidad. Lo que transmites importa; elige con cuidado.',
    consejo_personal: 'Ansuz gnósticamente es el Logos, la palabra creadora que ordena el caos en cosmos. Tu misión es ser oído limpio para recibir y voz clara para transmitir la sabiduría que llega a través de ti.',
    desc_anual: 'En este año, Ansuz abre los canales de comunicación y de inspiración. Es un año en que lo que dices y cómo lo dices tendrá más peso de lo habitual. Presta atención a los mensajes que llegan en sueños, en conversaciones inesperadas y en los silencios. Hay información que necesitas recibir este año y también palabras que necesitas pronunciar.',
    consejo_anual: 'Ansuz en año personal pide que cuides el lenguaje que usas contigo mismo tanto como el que usas con otros. Las palabras que más te forman son las que nadie más escucha.',
    desc_dia: 'Ansuz en tu día de nacimiento imprime en tu carácter una relación especial con la palabra, la comunicación y la sabiduría transmitida. Naciste con el oído fino del mensajero: captas matices donde otros ven silencio, y tienes una capacidad innata para nombrar lo que los demás no pueden articular.',
    desc_mes: 'La runa del mes en que naciste es Ansuz, marcando ese ciclo con la vibración de la comunicación sagrada y la inspiración. Hay en tu manera de expresarte una calidad que trasciende lo meramente informativo: cuando hablas desde tu centro, lo que sale tiene el peso de algo verdadero.',
    desc_anio: 'Tu runa del año de nacimiento es Ansuz, hablando de una generación marcada por la misión de transmitir y comunicar verdades que otros prefieren no nombrar. Tu año de llegada vibraba con la frecuencia del mensajero divino. Los de tu generación tienen una facilidad para captar el espíritu de los tiempos y ponerle voz.'
  },
  5: {
    nombre: 'Raidho', simbolo: 'ᚱ',
    img: 'https://static.wixstatic.com/media/0bac9e_7d08460fc2f541cabc2f5a130bae9f23~mv2.png',
    desc_personal: 'Tu runa personal es Raidho, y te define como alguien esencialmente en movimiento. Tu personalidad no fue diseñada para quedarse quieta: eres el viajero, el que hace camino al andar, el que encuentra el sentido en la jornada tanto como en el destino. Tienes un ritmo interno que cuando es respetado te lleva exactamente donde necesitas estar. Cuando te detienen o te detienen, algo en ti se apaga.',
    consejo_personal: 'Raidho gnósticamente es el alma en su peregrinaje cósmico. Cada etapa de tu vida es una jornada de iniciación. El ritmo que marcas con tu camino es también el ritmo del universo conociéndose a sí mismo.',
    desc_anual: 'En este año, Raidho marca una etapa de movimiento con propósito. No cualquier movimiento: este año pide que avances en una dirección real, que el viaje tenga sentido y no solo velocidad. Puede haber desplazamientos físicos, pero también viajes interiores de considerable importancia. Lo que recorres este año define el mapa de los próximos años.',
    consejo_anual: 'Raidho en año personal pregunta: ¿hacia dónde vas realmente? No confundas actividad con avance. El movimiento que importa este año es el que tiene dirección.',
    desc_dia: 'Raidho en tu día de nacimiento sella tu carácter con una vocación innata por el movimiento y la búsqueda. Naciste con el pie del viajero: algo en ti siempre está orientado hacia el horizonte, siempre hay una próxima etapa que llama. Este sello del día habla de alguien que aprende en el camino más que en la quietud.',
    desc_mes: 'La runa del mes en que naciste es Raidho, marcando ese ciclo estacional con la energía del desplazamiento, el ritmo y el camino. Hay en tu manera de transitar la vida una fluidez que otros encuentran envidiable: sabes cuándo es tiempo de partir y cuándo de quedarse, aunque no siempre puedas explicar cómo lo sabes.',
    desc_anio: 'Tu runa del año de nacimiento es Raidho, hablando de una generación que llegó al mundo en movimiento, en un tiempo de transiciones y desplazamientos colectivos. Tu año de llegada vibraba con la frecuencia del viaje y el ritmo. Los de tu generación comparten una inquietud vital que los lleva a recorrer más etapas que el promedio.'
  },
  6: {
    nombre: 'Kenaz', simbolo: 'ᚲ',
    img: 'https://static.wixstatic.com/media/0bac9e_d36a287bfd6e430b90299e97e2087763~mv2.png',
    desc_personal: 'Tu runa personal es Kenaz, y te define como alguien que lleva una antorcha interior que puede iluminar lo que está oscuro para los demás. Tu personalidad tiene una calidad de claridad que no es arrogancia sino luz: ves lo que otros no ven, conectas puntos que parecen inconexos, y tienes una capacidad para el conocimiento práctico que se convierte en guía cuando lo compartes. El reto es mantener la llama encendida cuando el viento es fuerte.',
    consejo_personal: 'Kenaz gnósticamente es la luz gnóstica por excelencia: el conocimiento que no es información sino transformación. Lo que sabes de verdad, lo que has vivido y no solo leído, tiene el poder de iluminar a otros.',
    desc_anual: 'En este año, Kenaz ilumina lo que estaba en sombra. Es un año de revelaciones: algo que no entendías se vuelve claro, algo que ocultabas —consciente o inconscientemente— sale a la luz. No temas esa claridad. Lo que este año revela es lo que necesitas ver para avanzar con honestidad.',
    consejo_anual: 'Kenaz en año personal trae la luz del conocimiento a los rincones que preferías no mirar. Lo que ves claramente este año puedes transformarlo; lo que mantienes en la oscuridad sigue gobernando desde allí.',
    desc_dia: 'Kenaz en tu día de nacimiento imprime en tu carácter una inteligencia práctica y una capacidad de iluminar lo complejo. Naciste con la antorcha encendida: tienes una facilidad innata para encontrar claridad donde otros ven confusión, y para transmitir lo que sabes de manera que los demás puedan usarlo.',
    desc_mes: 'La runa del mes en que naciste es Kenaz, marcando ese ciclo con la vibración del fuego controlado y el conocimiento aplicado. Hay en tu manera de aprender y enseñar algo de artesano: no te conformas con saber en abstracto, necesitas saber para hacer, para transformar, para que el conocimiento aterrice en algo real.',
    desc_anio: 'Tu runa del año de nacimiento es Kenaz, hablando de una generación que vino al mundo con la misión de iluminar y enseñar. Tu año de llegada vibraba con la frecuencia del conocimiento que transforma. Los de tu generación son maestros innatos, aunque no siempre en el sentido formal: enseñan con lo que son tanto como con lo que dicen.'
  },
  7: {
    nombre: 'Gebo', simbolo: 'ᚷ',
    img: 'https://static.wixstatic.com/media/0bac9e_5cde3ad971f442c0b287ba829fe50d30~mv2.png',
    desc_personal: 'Tu runa personal es Gebo, y te define como alguien cuya naturaleza más profunda se expresa en el intercambio. Tu personalidad entiende instintivamente la ley del equilibrio en las relaciones: dar y recibir no son actos separados sino las dos caras de un mismo movimiento sagrado. Eres generoso, pero cuando estás en tu centro no pierdes de vista que cada don tiene su respuesta y que las relaciones sanas son las que fluyen en ambas direcciones.',
    consejo_personal: 'Gebo gnósticamente enseña que la generosidad más elevada no es dar lo que sobra sino compartir lo que eres. Cada encuentro verdadero es un intercambio sagrado donde ambas partes cambian.',
    desc_anual: 'En este año, Gebo pone el foco en los intercambios — en lo que das y en lo que recibes, y en si esos flujos están en equilibrio. Es un año de relaciones importantes, de acuerdos que pueden marcar el futuro y de tomar consciencia de dónde hay desequilibrios en tus vínculos. Lo que ofreces este año con autenticidad regresa multiplicado.',
    consejo_anual: 'Gebo en año personal te invita a revisar tus intercambios: ¿hay relaciones donde solo das o solo recibes? El equilibrio que establezcas este año en tus vínculos define la calidad de lo que construyes con otros.',
    desc_dia: 'Gebo en tu día de nacimiento sella tu carácter con un sentido innato de la reciprocidad y el don. Naciste con la comprensión de que las relaciones más verdaderas son intercambios donde nadie pierde y nadie se queda sin nada. Este sello del día habla de alguien que sabe dar y que también, cuando está en su centro, sabe recibir.',
    desc_mes: 'La runa del mes en que naciste es Gebo, marcando ese ciclo con la energía del don y del vínculo equilibrado. Hay en tu manera de relacionarte algo de ritual: las conexiones que haces no son casuales para ti, tienen peso, tienen significado, y cuando son recíprocas tienen una solidez que pocas cosas en tu vida pueden igualar.',
    desc_anio: 'Tu runa del año de nacimiento es Gebo, hablando de una generación marcada por la búsqueda del intercambio justo y los vínculos auténticos. Tu año de llegada vibraba con la frecuencia de la reciprocidad. Los de tu generación tienen una sensibilidad especial hacia la justicia en las relaciones y una incomodidad visceral ante los desequilibrios de poder.'
  },
  8: {
    nombre: 'Wunjo', simbolo: 'ᚹ',
    img: 'https://static.wixstatic.com/media/0bac9e_f7f0ec69973f496ba19760d00be99874~mv2.png',
    desc_personal: 'Tu runa personal es Wunjo, y te define como alguien cuya naturaleza más profunda busca la alegría genuina y la pertenencia real. Tu personalidad no es superficial: cuando estás en tu lugar, con las personas correctas y haciendo lo que te importa, irradias una alegría que no necesita palabras. Y cuando no estás en ese lugar, lo sabes con la misma claridad. Tienes un barómetro interno muy fino para la armonía y el bienestar.',
    consejo_personal: 'Wunjo gnósticamente es el estado del alma cuando ha encontrado su vibración natural. La alegría profunda no viene de las circunstancias sino del alineamiento entre el ser que eres y la vida que vives.',
    desc_anual: 'En este año, Wunjo anuncia un período de mayor armonía y satisfacción. No es el año del esfuerzo titánico sino el año en que lo sembrado empieza a dar fruto visible. Hay espacio para la alegría, para el reconocimiento y para disfrutar de lo que has construido. Permítete recibir el bienestar que este año ofrece sin minimizarlo ni sabotearlo.',
    consejo_anual: 'Wunjo en año personal te recuerda que mereces el bienestar que estás experimentando. No lo hagas pequeño. La alegría que sientes este año es el resultado de decisiones que tomaste antes.',
    desc_dia: 'Wunjo en tu día de nacimiento imprime en tu carácter una capacidad para la alegría y la conexión que no es ingenuidad sino don. Naciste con el sentido de la pertenencia encendido: sabes cuándo estás en el lugar correcto y cuándo no, y tienes una facilidad para crear atmósferas de armonía donde la gente se siente a gusto.',
    desc_mes: 'La runa del mes en que naciste es Wunjo, marcando ese ciclo con la vibración de la celebración, la tribu y la alegría compartida. Hay en tu manera de estar con los demás una calidez natural que hace que las personas quieran estar cerca de ti, no por lo que tienes sino por cómo las haces sentir.',
    desc_anio: 'Tu runa del año de nacimiento es Wunjo, hablando de una generación que vino al mundo en un tiempo de reconstrucción de vínculos y búsqueda de sentido colectivo. Tu año de llegada vibraba con la frecuencia de la alegría ganada, no regalada. Los de tu generación comprenden que el bienestar real requiere ser construido y elegido.'
  },
  9: {
    nombre: 'Hagalaz', simbolo: 'ᚺ',
    img: 'https://static.wixstatic.com/media/0bac9e_b595781b17dc4827b4acc4000411dae9~mv2.png',
    desc_personal: 'Tu runa personal es Hagalaz, y te define como alguien que lleva en su naturaleza la energía del granizo: la fuerza que destruye para que lo nuevo pueda nacer. Tu personalidad no es destructiva, pero tampoco es cómoda para quienes prefieren que nada cambie. Eres un agente de transformación aunque no lo elijas conscientemente. Los ciclos en tu vida tienden a cerrarse con más intensidad que en otros, y las crisis que atraviesas tienen un poder de renovación que con el tiempo se vuelve inconfundible.',
    consejo_personal: 'Hagalaz gnósticamente es la tormenta cósmica que precede al orden superior. Lo que se rompe en tu vida tiene siempre una razón más profunda de lo que la mente puede ver en el momento. Confía en el proceso.',
    desc_anual: 'En este año, Hagalaz anuncia interrupciones y cambios que llegan sin haber sido planificados. No es un año para aferrarse a lo que ya no funciona: el granizo no negocia. Lo que este año se rompe estaba pidiendo ser renovado. Cuanto antes sueltes lo que se va, antes puedes ver lo que viene.',
    consejo_anual: 'Hagalaz en año personal no es una sentencia de dificultad sino una promesa de limpieza. Lo que cae este año cae porque ya no te servía, aunque todavía no lo vieras.',
    desc_dia: 'Hagalaz en tu día de nacimiento sella tu carácter con una relación especial con la transformación y la ruptura. Naciste con la energía del cambio disruptivo en tu centro: tiendes a atraer situaciones que ponen a prueba tu capacidad de adaptación, y tu mayor fuerza es precisamente que sabes levantarte después de cada granizada con algo nuevo en las manos.',
    desc_mes: 'La runa del mes en que naciste es Hagalaz, marcando ese ciclo con la vibración de la transformación a través de la crisis. Hay en tu manera de manejar las dificultades algo de veterano: las tormentas no te sorprenden del todo porque llevas el sello de la tormenta desde que naciste.',
    desc_anio: 'Tu runa del año de nacimiento es Hagalaz, hablando de una generación que llegó al mundo en un tiempo de rupturas y renovaciones colectivas. Tu año de llegada vibraba con la frecuencia del cambio necesario. Los de tu generación tienen una resiliencia particular y una comprensión visceral de que de las crisis nacen las transformaciones más profundas.'
  },
  10: {
    nombre: 'Nauthiz', simbolo: 'ᚾ',
    img: 'https://static.wixstatic.com/media/0bac9e_e7a197b1ac8c4aabb88fa0efadaf88a1~mv2.png',
    desc_personal: 'Tu runa personal es Nauthiz, y te define como alguien forjado por la necesidad y la fricción. Tu personalidad tiene algo de diamante: la presión que habrías preferido no tener es exactamente lo que te dio tu dureza y tu brillo. No eres alguien que huye de las dificultades —aunque a veces lo deseas— porque en algún nivel profundo sabes que son tus maestras. Tienes una creatividad que se activa precisamente cuando los recursos son escasos.',
    consejo_personal: 'Nauthiz gnósticamente es la presión que forma el diamante. Sin resistencia no hay crecimiento. Sin necesidad no hay invención. Lee en cada limitación la pregunta que el universo te hace.',
    desc_anual: 'En este año, Nauthiz señala un período en que las limitaciones son parte del paisaje. No es un año de abundancia fácil sino de creatividad obligada. Lo que no puedes tener de la manera habitual, este año lo encontrarás de otra forma. La restricción que sientes no es una negativa: es una redirección.',
    consejo_anual: 'Nauthiz en año personal enseña que los años de necesidad son los que más te desarrollan. Lo que construyes con recursos limitados tiene una solidez que lo que construyes con abundancia raramente iguala.',
    desc_dia: 'Nauthiz en tu día de nacimiento imprime en tu carácter una relación especial con la necesidad como maestra. Naciste con el fuego de la fricción en tu centro: tu fuerza no viene de la facilidad sino de saber qué hacer cuando las cosas no son fáciles. Esa capacidad de encender fuego cuando hace frío es uno de tus dones más reales.',
    desc_mes: 'La runa del mes en que naciste es Nauthiz, marcando ese ciclo con la vibración de la restricción creativa y la sabiduría que nace de la escasez. Hay en tu manera de resolver problemas algo de ingeniero: encuentras el camino cuando otros ven un muro porque llevas en tu ADN energético la certeza de que la necesidad siempre encuentra su respuesta.',
    desc_anio: 'Tu runa del año de nacimiento es Nauthiz, hablando de una generación que llegó al mundo en un tiempo de carencias y reinvenciones. Tu año de llegada vibraba con la frecuencia de la creatividad nacida de la necesidad. Los de tu generación tienen una resiliencia y una inventiva particulares, y una relación con la escasez que otros encuentran difícil de entender.'
  },
  11: {
    nombre: 'Isa', simbolo: 'ᛁ',
    img: 'https://static.wixstatic.com/media/0bac9e_606fca47ae1c4386b2cf4bea203d8621~mv2.png',
    desc_personal: 'Tu runa personal es Isa, y te define como alguien con una profunda capacidad para la quietud y la contemplación. Tu personalidad puede parecer fría o distante desde fuera, pero lo que los demás llaman frialdad es en realidad la precisión del hielo: la claridad que se forma cuando las aguas se detienen. Tienes una capacidad de mantenerte firme cuando todo se mueve que es uno de tus dones más poderosos, aunque también puede convertirse en rigidez si no se trabaja.',
    consejo_personal: 'Isa gnósticamente es el estado contemplativo más extremo: la inmovilidad perfecta que precede la acción más precisa. Lo que el mundo llama estancamiento, el gnóstico en Isa reconoce como preparación profunda.',
    desc_anual: 'En este año, Isa pide quietud. No es un año para forzar el movimiento: es un año para dejar que las cosas cristalicen, para entender antes de actuar y para encontrar la solidez interior que te permitirá moverse con precisión cuando llegue el momento. Resiste la urgencia de hacer por hacer. Lo que se forma lentamente bajo el hielo puede ser la estructura más sólida que has construido.',
    consejo_anual: 'Isa en año personal enseña la diferencia entre estancamiento y consolidación. Lo que este año parece no moverse está adquiriendo la precisión que necesita para durar.',
    desc_dia: 'Isa en tu día de nacimiento sella tu carácter con una capacidad innata para la quietud y la concentración. Naciste con el don del hielo: puedes mantenerte inmóvil cuando todo se agita, puedes encontrar calma en el caos y puedes ver con claridad precisamente cuando las emociones de los demás los nublan.',
    desc_mes: 'La runa del mes en que naciste es Isa, marcando ese ciclo con la vibración de la cristalización y la quietud necesaria. Hay en tu manera de procesar las experiencias algo de lento y profundo que puede exasperar a los más impacientes, pero lo que integras lo integras de verdad: las cosas que aprendes las aprendes para siempre.',
    desc_anio: 'Tu runa del año de nacimiento es Isa, hablando de una generación que llegó al mundo en un tiempo de pausa y recogimiento. Tu año de llegada vibraba con la frecuencia de la solidificación y la contemplación. Los de tu generación tienen una profundidad interior notable y una capacidad para encontrar quietud incluso en circunstancias externas agitadas.'
  },
  12: {
    nombre: 'Jera', simbolo: 'ᛃ',
    img: 'https://static.wixstatic.com/media/0bac9e_3609d35b16b64904ab475405916a633b~mv2.png',
    desc_personal: 'Tu runa personal es Jera, y te define como alguien que entiende los ciclos en un nivel que va más allá de lo intelectual. Tu personalidad tiene la paciencia del agricultor: sabes que lo que se planta bien, cuando llega su tiempo, da fruto. No eres ingenuo respecto al esfuerzo que requiere lo que vale, pero tampoco eres ansioso: hay en ti una confianza profunda en que los ritmos naturales siempre entregan lo que corresponde.',
    consejo_personal: 'Jera gnósticamente es la comprensión de que el cosmos tiene sus propios ritmos y que alinearse con ellos es más poderoso que intentar forzarlos. Tu cosecha está creciendo aunque todavía no la veas.',
    desc_anual: 'En este año, Jera trae la cosecha de lo que has sembrado. Lo que has trabajado con consistencia empieza a mostrar sus frutos, y lo que has descuidado también muestra sus consecuencias. Es un año de justicia cósmica en el sentido más neutro: cada cosa vuelve en la proporción en que fue sembrada. Es un buen año para cosechar y también para plantar lo que quieres que madure en el próximo ciclo.',
    consejo_anual: 'Jera en año personal confirma que los tiempos del cosmos no son los de la impaciencia. Lo que recibes este año es lo que sembraste. Lo que siembras este año es lo que recibirás.',
    desc_dia: 'Jera en tu día de nacimiento imprime en tu carácter un sentido innato de los ciclos y los ritmos naturales. Naciste con la sabiduría del año completo en tu centro: comprendes que cada etapa tiene su tiempo y que apresurar lo que no está maduro solo produce fruto amargo. Esta paciencia tuya no es pasividad; es sabiduría.',
    desc_mes: 'La runa del mes en que naciste es Jera, marcando ese ciclo con la vibración de la cosecha y la justicia que devuelve lo sembrado. Hay en tu manera de trabajar algo de agricultor consciente: no esperas resultados inmediatos, pero tampoco plantas sin intención. Lo que construyes tiende a durar precisamente porque respetas los tiempos.',
    desc_anio: 'Tu runa del año de nacimiento es Jera, hablando de una generación que llegó al mundo en un tiempo de cosechas y balance de cuentas colectivas. Tu año de llegada vibraba con la frecuencia de la justicia y los ciclos completados. Los de tu generación tienen una comprensión especial de la causa y el efecto, y una tendencia a mirar la historia en ciclos largos más que en eventos aislados.'
  },
  13: {
    nombre: 'Eihwaz', simbolo: 'ᛇ',
    img: 'https://static.wixstatic.com/media/0bac9e_129f808c50ba4a02944ca3a7cddd7a83~mv2.png',
    desc_personal: 'Tu runa personal es Eihwaz, y te define como alguien que vive entre mundos. Tu personalidad tiene la profundidad del tejo: un árbol que tiene raíces en la muerte y ramas en la vida, que puede vivir siglos precisamente porque no teme a lo que acaba. Hay en ti una resistencia que no es dureza sino elasticidad profunda, y un acceso a capas de la experiencia que muchos nunca tocan porque les da miedo ir tan adentro.',
    consejo_personal: 'Eihwaz gnósticamente es el eje del cosmos, el árbol de la vida en su versión más oscura y más sabia. Eres alguien que puede moverse entre mundos, que no teme a la sombra porque la conoce.',
    desc_anual: 'En este año, Eihwaz señala una etapa de profundización que puede implicar contacto con lo que muere, lo que se transforma y lo que renace. No es un año superficial. Algo en tu vida puede llegar a su final para que algo más real pueda comenzar. No huyas de esa profundidad: ahí está lo que necesitas encontrar.',
    consejo_anual: 'Eihwaz en año personal te lleva al centro del árbol. Lo que este año se muere era la corteza. Lo que nace es la médula. Confía en la profundidad del proceso.',
    desc_dia: 'Eihwaz en tu día de nacimiento sella tu carácter con una conexión especial a las capas más profundas de la experiencia. Naciste con el eje del mundo en tu centro: tienes acceso a una sabiduría que no aprendiste sino que traes, una resistencia ante la adversidad que no se explica por lo vivido solamente.',
    desc_mes: 'La runa del mes en que naciste es Eihwaz, marcando ese ciclo con la vibración del umbral y la transformación profunda. Hay en tu manera de procesar las pérdidas y los finales algo de alquimista: lo que para otros es solo dolor, para ti contiene una transmutación que con el tiempo da frutos que ningún camino más cómodo podría dar.',
    desc_anio: 'Tu runa del año de nacimiento es Eihwaz, hablando de una generación marcada por la transformación a través de la profundidad. Tu año de llegada vibraba con la frecuencia del árbol que vive entre mundos. Los de tu generación tienen una relación especial con la muerte y el renacimiento, con los finales que son comienzos disfrazados.'
  },
  14: {
    nombre: 'Perthro', simbolo: 'ᛈ',
    img: 'https://static.wixstatic.com/media/0bac9e_050ffef4161e4f5083a6d0ea97a1dbe1~mv2.png',
    desc_personal: 'Tu runa personal es Perthro, y te define como alguien que camina con el misterio. Tu personalidad tiene una profundidad que no puede ser completamente cartografiada, ni por los demás ni por ti mismo. Hay fuerzas que operan en tu vida que trascienden el cálculo y la planificación, y esto no es una debilidad: es la libertad del misterio que habita en ti. Lo inesperado no te visita por accidente; es parte de tu naturaleza.',
    consejo_personal: 'Perthro gnósticamente es el conocimiento de que hay fuerzas más grandes que la voluntad individual operando en tu vida. Rendirse al misterio no es pasividad: es la apertura que permite que lo extraordinario suceda.',
    desc_anual: 'En este año, Perthro anuncia lo inesperado. No en el sentido de caos sino en el sentido de lo que no podías haber calculado. Este año trae sorpresas, giros imprevistos y revelaciones sobre lo que realmente está en juego en tu vida. Lo que creías saber puede mostrar una cara que no habías visto. Mantente abierto.',
    consejo_anual: 'Perthro en año personal sugiere que aflojar el control este año es más sabio que apretarlo. Lo que el destino tiene preparado para ti este año supera lo que tu plan podría ofrecerte.',
    desc_dia: 'Perthro en tu día de nacimiento imprime en tu carácter una relación especial con el azar y el destino. Naciste con el dado del oráculo en tu centro: hay una dimensión de tu vida que siempre escapa al control total, y esa dimensión —cuando la aceptas— es la que te conecta con las posibilidades más extraordinarias.',
    desc_mes: 'La runa del mes en que naciste es Perthro, marcando ese ciclo con la vibración del misterio y lo que aún no tiene forma. Hay en tu manera de anticipar el futuro una combinación peculiar de intuición aguda y aceptación del no-saber que te da una flexibilidad ante lo imprevisto que otros no tienen.',
    desc_anio: 'Tu runa del año de nacimiento es Perthro, hablando de una generación que llegó al mundo en un tiempo de incertidumbre y transformación de paradigmas. Tu año de llegada vibraba con la frecuencia del misterio y lo impredecible. Los de tu generación tienen una relación más cómoda con la ambigüedad y una comprensión de que no todo puede ni debe ser controlado.'
  },
  15: {
    nombre: 'Algiz', simbolo: 'ᛉ',
    img: 'https://static.wixstatic.com/media/0bac9e_9a4e718ea6bc46ac89ad30a3311138e4~mv2.png',
    desc_personal: 'Tu runa personal es Algiz, y te define como alguien que lleva consigo una protección que no necesita ser pedida porque es consecuencia de quién eres. Tu personalidad tiene la energía del escudo sagrado: cuando actúas desde tu verdad, hay una gracia que te rodea que otros pueden percibir aunque no puedan explicarla. Eres también alguien con una intuición protectora muy desarrollada, capaz de sentir cuando algo o alguien representa una amenaza antes de que sea visible.',
    consejo_personal: 'Algiz gnósticamente es la protección divina que rodea al iniciado sincero. Cuando vives alineado con tu propósito más profundo, hay una gracia que te rodea que es consecuencia natural de tu integridad.',
    desc_anual: 'En este año, Algiz activa una protección especial a tu alrededor. No es que no puedan llegar dificultades, sino que tendrás una capacidad aumentada para sentir lo que viene antes de que llegue. Es un año para confiar en tu instinto, para fortalecer tus límites y para saber que lo que te impulsa desde la integridad te mantiene a salvo.',
    consejo_anual: 'Algiz en año personal te recuerda que tu mejor protección es tu autenticidad. Este año, alejarte de lo que no es verdadero para ti es también alejarte de lo que podría hacerte daño.',
    desc_dia: 'Algiz en tu día de nacimiento sella tu carácter con un sentido protector innato — hacia ti mismo y hacia quienes amas. Naciste con el escudo encendido: tienes un radar para el peligro y una capacidad de sostener a los tuyos en los momentos difíciles que nace de algo más profundo que la experiencia acumulada.',
    desc_mes: 'La runa del mes en que naciste es Algiz, marcando ese ciclo con la vibración de la protección y el vínculo con lo sagrado. Hay en tu manera de relacionarte con el mundo un instinto conservador en el mejor sentido: no porque seas miedoso, sino porque tienes un sentido fino de lo que merece ser guardado y lo que merece ser soltado.',
    desc_anio: 'Tu runa del año de nacimiento es Algiz, hablando de una generación que llegó al mundo en un tiempo de protección de lo esencial. Tu año de llegada vibraba con la frecuencia del escudo y el umbral sagrado. Los de tu generación tienen una conciencia especial de los límites —los propios y los ajenos— y un instinto protector que se extiende más allá de sí mismos.'
  },
  16: {
    nombre: 'Sowilo', simbolo: 'ᛊ',
    img: 'https://static.wixstatic.com/media/0bac9e_98654fedf3674e4798588f4dffe6e5a2~mv2.png',
    desc_personal: 'Tu runa personal es Sowilo, y te define como alguien que lleva la energía del sol en su centro. Tu personalidad irradia cuando está encendida: tienes una capacidad de brillar que no es vanidad sino vocación natural, una orientación hacia la claridad y el éxito que no puede ser apagada indefinidamente por las circunstancias. Sowilo también es la runa de la guía: cuando estás en tu luz, otros se orientan por ti aunque no lo pidas.',
    consejo_personal: 'Sowilo gnósticamente es la chispa divina en su expresión más pura: el elemento solar que reside en el ser humano y que, cuando se activa, convierte al individuo en canal de luz cósmica.',
    desc_anual: 'En este año, Sowilo ilumina el camino. Es un año de claridad, de victorias que llegan después de esfuerzo sostenido y de reconocimiento de lo que has construido. Algo que buscabas encuentra la luz este año. Tu energía es solar este ciclo: úsala para avanzar en lo que más importa y para iluminar también a quienes caminan cerca.',
    consejo_anual: 'Sowilo en año personal es una promesa de claridad. Lo que no podías ver sobre ti mismo y tu camino este año se vuelve visible. Aprovecha esa claridad para tomar decisiones que en otros momentos habrían sido más difíciles.',
    desc_dia: 'Sowilo en tu día de nacimiento imprime en tu carácter una calidad solar innata. Naciste con la guía del sol en tu centro: tienes una orientación natural hacia lo que da vida, una capacidad de brillar en los momentos difíciles y una energía de victoria que se activa precisamente cuando más se necesita.',
    desc_mes: 'La runa del mes en que naciste es Sowilo, marcando ese ciclo con la vibración de la luz solar y la claridad. Hay en tu manera de atravesar los períodos oscuros algo de fe solar: sabes, aunque no siempre racionalmente, que el sol siempre vuelve. Esa certeza es uno de los recursos más sólidos que tienes.',
    desc_anio: 'Tu runa del año de nacimiento es Sowilo, hablando de una generación que llegó al mundo en un tiempo de iluminación y renovación solar. Tu año de llegada vibraba con la frecuencia del sol en su plenitud. Los de tu generación tienen una fuerza de voluntad y una orientación hacia la claridad que los hace especialmente efectivos cuando encuentran su misión.'
  },
  17: {
    nombre: 'Tiwaz', simbolo: 'ᛏ',
    img: 'https://static.wixstatic.com/media/0bac9e_7d4f855234934f1a8334c5eb8d03bf02~mv2.png',
    desc_personal: 'Tu runa personal es Tiwaz, y te define como alguien que lleva el arquetipo del guerrero justo en su núcleo. Tu personalidad tiene una orientación innata hacia la verdad y la justicia que no puede ser callada del todo: cuando algo es injusto, lo percibes y lo dices aunque te cueste. Como Tyr, estás dispuesto a perder algo propio si eso es lo que requiere hacer lo correcto. Esa integridad es tu fuerza más profunda.',
    consejo_personal: 'Tiwaz gnósticamente es el arquetipo del guerrero espiritual: aquel que pelea no por gloria sino por verdad, dispuesto a perder en lo personal lo que sea necesario para ganar en el plano del alma.',
    desc_anual: 'En este año, Tiwaz llama al combate justo. Puede haber situaciones que requieran que defiendas lo que es correcto, aunque eso implique un costo personal. Es un año para desarrollar el coraje no de la confrontación sino de la integridad: hacer lo que es verdadero aunque sea incómodo, sostener tus valores cuando son cuestionados.',
    consejo_anual: 'Tiwaz en año personal te pregunta: ¿por qué luchas este año? La dirección de tu energía guerrera determina si este año construyes o solo desgastas. Elige tus batallas desde la verdad, no desde el ego.',
    desc_dia: 'Tiwaz en tu día de nacimiento sella tu carácter con una disposición innata hacia la justicia y el sacrificio consciente. Naciste con la flecha del guerrero en tu centro: tienes un sentido de lo correcto que va más allá de las convenciones sociales y una valentía para actuar desde ese sentido aunque el precio sea alto.',
    desc_mes: 'La runa del mes en que naciste es Tiwaz, marcando ese ciclo con la vibración de la justicia y el coraje. Hay en tu manera de enfrentar los conflictos algo de soldado honesto: no te gusta la confrontación innecesaria, pero tampoco huyes cuando algo importante está en juego.',
    desc_anio: 'Tu runa del año de nacimiento es Tiwaz, hablando de una generación marcada por la lucha por la justicia y la verdad colectiva. Tu año de llegada vibraba con la frecuencia del guerrero que sirve a algo más grande que sí mismo. Los de tu generación tienen una conciencia social aguda y una incomodidad visceral ante la injusticia que los empuja a actuar.'
  },
  18: {
    nombre: 'Berkano', simbolo: 'ᛒ',
    img: 'https://static.wixstatic.com/media/0bac9e_c763a71b6685496eb327e4417609662d~mv2.png',
    desc_personal: 'Tu runa personal es Berkano, y te define como alguien con una profunda capacidad de nutrir, regenerar y dar inicio a lo nuevo. Tu personalidad tiene la energía del abedul: aparece después de la tormenta, crece donde otros no pueden y prepara el terreno para lo que viene. Hay en ti un don para criar, para cuidar y para crear las condiciones en que las cosas florecen, sean personas, proyectos o ideas.',
    consejo_personal: 'Berkano gnósticamente es el principio femenino de la creación: la capacidad de dar forma, nutrir y sostener la vida. Tu misión es crear las condiciones para que lo nuevo pueda nacer y crecer sin ser asfixiado por lo viejo.',
    desc_anual: 'En este año, Berkano anuncia nuevos comienzos que emergen de lo que terminó. Es un año de nacimientos —de proyectos, de relaciones, de versiones de ti mismo que estaban gestándose en silencio. Lo que empieza este año llega con frescura y potencial. Cuídalo con la misma atención que darías a algo recién nacido.',
    consejo_anual: 'Berkano en año personal señala que lo que empieza este año es frágil pero real. Dale el tiempo y el cuidado que necesita sin apresurarlo. Las mejores raíces crecen despacio.',
    desc_dia: 'Berkano en tu día de nacimiento imprime en tu carácter una capacidad regeneradora innata. Naciste con la energía de la madre tierra en tu centro: tienes un don para hacer que las cosas vivan, para encontrar lo que puede nacer incluso en los terrenos más áridos, y para nutrir lo nuevo con una paciencia que no todo el mundo posee.',
    desc_mes: 'La runa del mes en que naciste es Berkano, marcando ese ciclo con la vibración del nacimiento y la renovación. Hay en tu manera de cerrar etapas algo de natural y orgánico: cuando algo termina en tu vida, casi siempre algo nuevo empieza a brotar sin que tengas que forzarlo. Confías —aunque a veces con dificultad— en que después de cada invierno hay un abedul.',
    desc_anio: 'Tu runa del año de nacimiento es Berkano, hablando de una generación que llegó al mundo en un tiempo de renovación y nuevos comienzos colectivos. Tu año de llegada vibraba con la frecuencia del primer brote después del invierno. Los de tu generación tienen una capacidad especial para encontrar posibilidad donde otros solo ven ruinas.'
  },
  19: {
    nombre: 'Ehwaz', simbolo: 'ᛖ',
    img: 'https://static.wixstatic.com/media/0bac9e_77d19fa6c4324005825455c77c209cb2~mv2.png',
    desc_personal: 'Tu runa personal es Ehwaz, y te define como alguien cuya naturaleza más profunda se activa en alianza. Tu personalidad no es solitaria en su esencia: eres el jinete y el caballo al mismo tiempo, la fuerza que se multiplica cuando encuentra su compañero de camino. Tienes un don especial para la sincronía con otros, para moverte al unísono con quien te complementa y para construir en conjunto lo que ninguno de los dos podría alcanzar solo.',
    consejo_personal: 'Ehwaz gnósticamente es la comprensión de que algunas etapas del camino espiritual requieren compañía, que hay verdades que solo se descubren en el espejo del otro.',
    desc_anual: 'En este año, Ehwaz pone el foco en las alianzas y el movimiento compartido. Es un año en que las relaciones de confianza cobran protagonismo, en que lo que construyes con otros tiene más peso que lo que haces en solitario. Busca al compañero de viaje que este año te falta y suelta las alianzas que ya no marchan al mismo ritmo.',
    consejo_anual: 'Ehwaz en año personal sugiere que este año no es para andar solo. La sincronía que buscas con otro ser —en cualquier ámbito— es parte de lo que este ciclo tiene para ofrecerte.',
    desc_dia: 'Ehwaz en tu día de nacimiento sella tu carácter con una aptitud innata para la alianza y el movimiento conjunto. Naciste con el ritmo del caballo y el jinete en tu centro: sabes cuándo liderar y cuándo dejarte llevar, y tienes una sensibilidad para la sincronía con otros que hace que las cosas fluyan de una manera especial cuando encuentras a tu par.',
    desc_mes: 'La runa del mes en que naciste es Ehwaz, marcando ese ciclo con la vibración del viaje en compañía y la alianza que multiplica. Hay en tu manera de trabajar con otros algo de coreografía natural: cuando la persona o el equipo es el correcto, te mueves con una elegancia y una eficiencia que en solitario raramente alcanzas.',
    desc_anio: 'Tu runa del año de nacimiento es Ehwaz, hablando de una generación marcada por el valor de las alianzas y el movimiento colectivo. Tu año de llegada vibraba con la frecuencia del caballo y el jinete en perfecta sincronía. Los de tu generación comprenden instintivamente que hay etapas que no pueden recorrerse solos y tienen una apertura especial a la colaboración genuina.'
  },
  20: {
    nombre: 'Mannaz', simbolo: 'ᛗ',
    img: 'https://static.wixstatic.com/media/0bac9e_be5661413d2a4c4aa881157a43d79105~mv2.png',
    desc_personal: 'Tu runa personal es Mannaz, y te define como alguien cuyo camino pasa por el autoconocimiento a través del espejo de los demás. Tu personalidad es profundamente humana en el mejor sentido: tienes una conciencia de ti mismo que se afina en el contacto con otros, una capacidad de verte reflejado en quienes te rodean y de aprender de esas reflexiones sin perderte en ellas. Eres el observador de la condición humana, empezando por la tuya.',
    consejo_personal: 'Mannaz gnósticamente es la runa del ser que se conoce a sí mismo como chispa del todo. La frase délfica "Conócete a ti mismo" es su esencia. Tu camino pasa por entenderte para entender el cosmos.',
    desc_anual: 'En este año, Mannaz profundiza el autoconocimiento. Lo que descubres sobre ti mismo a través de las relaciones y las situaciones que este año te presenta es más valioso de lo que parece en el momento. Presta atención a lo que te incomoda en otros: suele ser lo que todavía no has integrado de ti mismo. Este año es una oportunidad de lucidez sobre quién eres.',
    consejo_anual: 'Mannaz en año personal te coloca frente al espejo. Lo que ves puede sorprenderte, pero lo que integras de esa visión te libera. El autoconocimiento que ganas este año no tiene precio.',
    desc_dia: 'Mannaz en tu día de nacimiento imprime en tu carácter una conciencia reflexiva innata. Naciste con la capacidad de observarte a ti mismo en acción, de preguntar quién eres más allá del rol y del nombre. Esa conciencia puede ser tu mayor fortaleza o tu mayor fuente de confusión dependiendo de cómo la uses.',
    desc_mes: 'La runa del mes en que naciste es Mannaz, marcando ese ciclo con la vibración de la conciencia humana en su dimensión más reflexiva. Hay en tu manera de relacionarte con el mundo una calidad de testigo: observas, procesas, integras. A veces esto te hace más lento que otros para actuar, pero lo que finalmente haces viene de un lugar de comprensión que otros raramente alcanzan.',
    desc_anio: 'Tu runa del año de nacimiento es Mannaz, hablando de una generación marcada por la búsqueda del autoconocimiento y la comprensión de la condición humana. Tu año de llegada vibraba con la frecuencia de la consciencia reflexiva. Los de tu generación tienen una profundidad psicológica particular y una tendencia a cuestionarse a sí mismos con una honestidad que puede ser incómoda pero que los lleva lejos.'
  },
  21: {
    nombre: 'Laguz', simbolo: 'ᛚ',
    img: 'https://static.wixstatic.com/media/0bac9e_9624226b25aa4707a681f8c6ee075bed~mv2.png',
    desc_personal: 'Tu runa personal es Laguz, y te define como alguien que vive con un pie en el mundo visible y otro en las profundidades invisibles. Tu personalidad tiene la naturaleza del agua: toma la forma del recipiente pero nunca pierde su esencia, puede ser calma o tormenta, puede nutrir o erosionar. Tienes una intuición que sabe cosas que la mente todavía no puede articular, y una vida emocional que es tan profunda como el mar en su parte más insondable.',
    consejo_personal: 'Laguz gnósticamente es el agua primordial de la que emerge toda vida, la fuente de la intuición que precede al conocimiento. Aprende a navegar tus profundidades sin perderte en ellas.',
    desc_anual: 'En este año, Laguz te invita a confiar en tus profundidades. Es un año en que la intuición es más confiable que el análisis, en que los sueños tienen mensajes importantes y en que lo que percibes en los silencios te dice más que lo que escuchas en el ruido. Nada en tu vida este año es solo lo que parece en la superficie.',
    consejo_anual: 'Laguz en año personal sugiere que este año el caudal interno tiene mucho que decirte. Crea espacio para escucharlo. Lo que emerja de tus profundidades este año puede orientar decisiones que el razonamiento solo no puede tomar.',
    desc_dia: 'Laguz en tu día de nacimiento sella tu carácter con una sensibilidad profunda y una conexión con el mundo invisible que viene de antes de la razón. Naciste con el flujo del agua en tu centro: eres receptivo sin ser pasivo, intuitivo sin ser irracional, y capaz de moverte a través de las emociones más intensas con una fluidez que otros no comprenden del todo.',
    desc_mes: 'La runa del mes en que naciste es Laguz, marcando ese ciclo con la vibración de los flujos subterráneos y la intuición que nace en las profundidades. Hay en tu manera de percibir el mundo algo de sonar submarino: captas lo que está debajo de la superficie antes de que llegue al nivel consciente, y esa capacidad es uno de tus recursos más valiosos.',
    desc_anio: 'Tu runa del año de nacimiento es Laguz, hablando de una generación marcada por la conexión con el mundo interior y los flujos emocionales colectivos. Tu año de llegada vibraba con la frecuencia del agua profunda. Los de tu generación tienen una inteligencia emocional particular y una sensibilidad a los estados colectivos del alma que los hace especialmente perceptivos en tiempos de cambio.'
  },
  22: {
    nombre: 'Ingwaz', simbolo: 'ᛜ',
    img: 'https://static.wixstatic.com/media/0bac9e_be408d5fc5da4a91bad0d49cc90415ad~mv2.png',
    desc_personal: 'Tu runa personal es Ingwaz, y te define como alguien que lleva un potencial todavía no completamente desplegado. Tu personalidad tiene la naturaleza de la semilla: hay en ti más de lo que muestras, más de lo que incluso tú sabes que hay. Eres un ser en proceso de germinar en su plenitud, y los períodos que parecen inactivos en tu vida suelen ser los de mayor gestación. No te compares con lo que ya floreció: tu tiempo tiene su propio ritmo.',
    consejo_personal: 'Ingwaz gnósticamente es la energía del ser que está completando una etapa antes de dar el salto. La aparente inactividad es en realidad la acumulación de todo lo que necesitas para el próximo ciclo.',
    desc_anual: 'En este año, Ingwaz señala un período de gestación y acumulación de energía. No es un año de grandes explosiones externas sino de preparación interna. Algo en ti está madurando para un próximo ciclo de manifestación. No lo apresures. Confía en lo que se está formando aunque todavía no tenga la forma que podrás reconocer.',
    consejo_anual: 'Ingwaz en año personal pide paciencia con tu propio proceso. Lo que este año parece quietud es semilla. Lo que ves como inactividad es acumulación. El próximo ciclo te sorprenderá si dejas que este complete su gestación.',
    desc_dia: 'Ingwaz en tu día de nacimiento imprime en tu carácter una calidad de potencial contenido que busca el momento justo para manifestarse. Naciste con la semilla de algo grande en tu centro, algo que requiere el tiempo y el terreno adecuados para germinar en su plenitud. No te desesperes en los períodos de aparente quietud: son tus tiempos de mayor preparación.',
    desc_mes: 'La runa del mes en que naciste es Ingwaz, marcando ese ciclo con la vibración del potencial que se acumula antes de manifestarse. Hay en tu manera de prepararte para lo que viene algo de naturaleza: no floreces en cualquier estación, pero cuando tu tiempo llega, el resultado es inconfundible.',
    desc_anio: 'Tu runa del año de nacimiento es Ingwaz, hablando de una generación que llegó al mundo cargada de un potencial que se manifiesta lentamente y con solidez. Tu año de llegada vibraba con la frecuencia de la semilla que espera. Los de tu generación tienen una tendencia a dar sus mejores frutos más tarde que temprano, y lo que construyen suele ser más duradero que lo que construyen quienes florecen más rápido.'
  },
  23: {
    nombre: 'Dagaz', simbolo: 'ᛞ',
    img: 'https://static.wixstatic.com/media/0bac9e_3ec767e0fd994a22974fa4a6a2a30f42~mv2.png',
    desc_personal: 'Tu runa personal es Dagaz, y te define como alguien que vive en el umbral entre lo que era y lo que puede ser. Tu personalidad tiene la naturaleza del amanecer: no perteneces del todo a la noche ni del todo al día, sino al momento exacto en que uno se convierte en otro. Tienes una capacidad de transformación súbita que sorprende incluso a quienes te conocen bien, y una orientación innata hacia la luz que no niega la oscuridad sino que la trasciende.',
    consejo_personal: 'Dagaz gnósticamente es el momento atemporal de la iluminación: el instante en que el velo se levanta y la realidad se ve tal como es. Estás diseñado para los umbrales. Atraviésalos con los ojos abiertos.',
    desc_anual: 'En este año, Dagaz marca un punto de inflexión mayor. Estás en un amanecer: lo que fue está dando paso a lo que será, y ese proceso no siempre es cómodo pero siempre es transformador. Este año puede traer un despertar, una comprensión que cambia tu perspectiva de manera irreversible. No temas lo que el alba revela.',
    consejo_anual: 'Dagaz en año personal anuncia que lo que cambia este año no puede ser deshecho: una vez que amanece, no puedes volver a no haber visto la luz. Lo que este año transforma, te transforma para siempre.',
    desc_dia: 'Dagaz en tu día de nacimiento sella tu carácter con una naturaleza de umbral y transformación. Naciste en el amanecer metafórico: llevas en ti la capacidad de pasar de un estado a otro con una rapidez que puede desconcertar a los demás pero que para ti es simplemente la forma en que funciona la realidad.',
    desc_mes: 'La runa del mes en que naciste es Dagaz, marcando ese ciclo con la vibración del punto de inflexión y el despertar. Hay en tu manera de atravesar los cambios algo de aurora: lo que para otros es oscuro o confuso, para ti tiene una calidad de transición que ya presiente la luz al otro lado.',
    desc_anio: 'Tu runa del año de nacimiento es Dagaz, hablando de una generación marcada por los grandes puntos de inflexión históricos y la transformación paradigmática. Tu año de llegada vibraba con la frecuencia del amanecer colectivo. Los de tu generación son portadores de una visión del mundo que trasciende los paradigmas anteriores, aunque no siempre sepan nombrarlo.'
  },
  24: {
    nombre: 'Othala', simbolo: 'ᛟ',
    img: 'https://static.wixstatic.com/media/0bac9e_cda902563baa466da7231dbc4902e563~mv2.png',
    desc_personal: 'Tu runa personal es Othala, y te define como alguien profundamente ligado a su linaje, a su tierra y a lo que heredó —en el más amplio sentido de la palabra. Tu personalidad tiene raíces: hay en ti una relación con los que vinieron antes que puede ser nutricia o limitante según cómo la trabajes. Tienes un sentido de pertenencia y continuidad que es tanto tu fortaleza como tu reto: discernir qué del pasado merece ser preservado y qué necesita ser transformado antes de ser transmitido.',
    consejo_personal: 'Othala gnósticamente es la conciencia de la cadena de almas a la que perteneces. Tu trabajo espiritual sana hacia atrás y libera hacia adelante. Lo que integras en ti mismo no lo heredan los que vienen después.',
    desc_anual: 'En este año, Othala pone el foco en el linaje y la herencia — no solo material sino emocional, cultural, espiritual. Es un año para revisar qué cargas ancestrales todavía llevas sin necesidad y qué dones heredados todavía no has reconocido. Es también un año para la tierra, para el hogar, para consolidar lo que quieres que dure más allá de ti.',
    consejo_anual: 'Othala en año personal te invita a honrar a los tuyos con lucidez: no todo lo que heredas merece ser perpetuado, y discernir esa diferencia este año es un acto de amor hacia tu linaje y hacia el futuro.',
    desc_dia: 'Othala en tu día de nacimiento sella tu carácter con una conexión profunda con el linaje y la pertenencia. Naciste con la memoria de los tuyos en tu centro: hay en ti algo que viene de antes, una sabiduría o una carga ancestral que forma parte de tu identidad más profunda y que requiere ser reconocida para ser bien utilizada.',
    desc_mes: 'La runa del mes en que naciste es Othala, marcando ese ciclo con la vibración de la herencia y la pertenencia a algo más grande que el individuo. Hay en tu manera de relacionarte con el pasado algo de guardián: no como quien se queda atrapado en él, sino como quien sabe que sin raíces no hay árbol que aguante la tormenta.',
    desc_anio: 'Tu runa del año de nacimiento es Othala, hablando de una generación marcada por la relación con el linaje y la herencia colectiva. Tu año de llegada vibraba con la frecuencia de la tierra y la continuidad. Los de tu generación tienen una conciencia especial de la deuda con el pasado y la responsabilidad hacia el futuro, y una tendencia a buscar sus raíces con una profundidad que las generaciones más jóvenes a veces no comprenden.'
  }
};