window._PERS_DATA = {
  intro: {
    aries:'iniciativa y fuego', tauro:'sensualidad y constancia', geminis:'ingenio y versatilidad',
    cancer:'emoción y cuidado', leo:'brillantez y liderazgo', virgo:'análisis y servicio',
    libra:'armonía y belleza', escorpio:'intensidad y transformación', sagitario:'expansión y libertad',
    capricornio:'ambición y disciplina', acuario:'originalidad y visión', piscis:'intuición y compasión'
  },
  luna: {
    aries:'reacciona con impulsividad y necesita acción inmediata para procesar sus emociones',
    tauro:'necesita estabilidad sensorial y seguridad material para sentirse en paz',
    geminis:'procesa sus emociones a través de la palabra y necesita variedad mental constante',
    cancer:'siente con profundidad oceánica y necesita un hogar emocional seguro',
    leo:'necesita reconocimiento y expresión dramática para sentirse emocionalmente vivo',
    virgo:'analiza sus emociones y encuentra calma en el orden y el servicio',
    libra:'necesita armonía relacional y justicia emocional para encontrar su centro',
    escorpio:'siente con intensidad abismal y necesita transformar el dolor en poder',
    sagitario:'necesita libertad emocional y optimismo para no sentirse atrapado',
    capricornio:'reprime las emociones bajo la lógica y necesita metas claras para sentirse seguro',
    acuario:'desapega emocionalmente por instinto y necesita independencia para abrirse',
    piscis:'absorbe el campo emocional de todos y necesita soledad para reconectarse consigo mismo'
  },
  asc: {
    aries:'proyecta energía directa, impulsiva y pionera al mundo',
    tauro:'proyecta una presencia calmante, sensual y confiable',
    geminis:'proyecta curiosidad, adaptabilidad y rapidez mental',
    cancer:'proyecta sensibilidad, calidez y cuidado instintivo',
    leo:'proyecta magnetismo, autoridad y generosidad natural',
    virgo:'proyecta precisión, discreción y servicio inteligente',
    libra:'proyecta elegancia, diplomacia y búsqueda de equilibrio',
    escorpio:'proyecta intensidad, misterio y magnetismo profundo',
    sagitario:'proyecta optimismo, aventura y filosofía de vida',
    capricornio:'proyecta madurez, ambición y solidez ante el mundo',
    acuario:'proyecta originalidad, independencia y visión de futuro',
    piscis:'proyecta suavidad, empatía y una presencia casi etérea'
  }
};

// DECAN_MESES / DECAN_LIMITES / DECAN_DATA
window._DECAN_MESES = {
  aries:      [{m:3,nombre:'Marzo',desde:21,hasta:31},{m:4,nombre:'Abril',desde:1,hasta:19}],
  tauro:      [{m:4,nombre:'Abril',desde:20,hasta:30},{m:5,nombre:'Mayo',desde:1,hasta:20}],
  geminis:    [{m:5,nombre:'Mayo',desde:21,hasta:31},{m:6,nombre:'Junio',desde:1,hasta:20}],
  cancer:     [{m:6,nombre:'Junio',desde:21,hasta:30},{m:7,nombre:'Julio',desde:1,hasta:22}],
  leo:        [{m:7,nombre:'Julio',desde:23,hasta:31},{m:8,nombre:'Agosto',desde:1,hasta:22}],
  virgo:      [{m:8,nombre:'Agosto',desde:23,hasta:31},{m:9,nombre:'Septiembre',desde:1,hasta:22}],
  libra:      [{m:9,nombre:'Septiembre',desde:23,hasta:30},{m:10,nombre:'Octubre',desde:1,hasta:22}],
  escorpio:   [{m:10,nombre:'Octubre',desde:23,hasta:31},{m:11,nombre:'Noviembre',desde:1,hasta:21}],
  sagitario:  [{m:11,nombre:'Noviembre',desde:22,hasta:30},{m:12,nombre:'Diciembre',desde:1,hasta:21}],
  capricornio:[{m:12,nombre:'Diciembre',desde:22,hasta:31},{m:1,nombre:'Enero',desde:1,hasta:19}],
  acuario:    [{m:1,nombre:'Enero',desde:20,hasta:31},{m:2,nombre:'Febrero',desde:1,hasta:19}],
  piscis:     [{m:2,nombre:'Febrero',desde:19,hasta:29},{m:3,nombre:'Marzo',desde:1,hasta:20}],
};

// Límites de decanatos (día inicio de cada uno dentro del signo)
window._DECAN_LIMITES = {
  aries:      [21,31,10], // 1°: 21mar-30mar | 2°: 31mar-9abr | 3°: 10abr-19abr — usaremos día absoluto del signo
  // En realidad calculamos por posición ordinal dentro del signo (días 1-10, 11-20, 21-30)
};

window._DECAN_DATA = {
  aries: {
    1: { titulo:'♈︎ Aries · Primer Decanato (Marte)', texto:'El primer decanato de Aries, regido por Marte en doble dominio, encarna la esencia más pura del signo. Naciste en el umbral del fuego: impulso sin filtro, valentía casi instintiva y una energía que abre caminos donde otros ven muros. Tu fuerza es tu arranque — cuando decides, actúas de inmediato. El desafío está en aprender a sostener lo que inicias, porque la llama que arde más fuerte al principio necesita combustible para durar.' },
    2: { titulo:'♈︎ Aries · Segundo Decanato (Sol)', texto:'El segundo decanato de Aries recibe la influencia del Sol, que ilumina el fuego ariano con conciencia y propósito. Tienes el impulso de Aries pero también la necesidad de ser reconocido y de construir algo con tu energía. No te basta con actuar: quieres que tu acción deje huella. Hay una vena creativa y lideresa que se activa cuando encuentras una causa que sientes verdaderamente tuya. Tu reto es no confundir el protagonismo con el ego.' },
    3: { titulo:'♈︎ Aries · Tercer Decanato (Júpiter)', texto:'El tercer decanato de Aries tiene a Júpiter como subreino, lo que da a este Aries una amplitud de miras poco común en el signo. Eres audaz como todo Aries, pero también visionario: no solo empiezas, sino que intuyes adónde puede llegar lo que empiezas. Tienes un optimismo expansivo y cierta filosofía natural que te hace buscar el sentido detrás de la acción. Tu reto es la impaciencia cuando la realidad tarda en alcanzar tu visión.' },
  },
  tauro: {
    1: { titulo:'♉︎ Tauro · Primer Decanato (Venus)', texto:'El primer decanato de Tauro, bajo el doble dominio de Venus, es la expresión más sensorial y plena del signo. Tienes un vínculo profundo con la belleza, el placer y el mundo material: sabes elegir, saborear y crear entornos que nutren. Tu presencia tiene una calidad reconfortante que atrae a los demás de forma natural. El desafío es la resistencia al cambio — cuando algo te da seguridad, puede costarte soltarlo incluso cuando ya no sirve.' },
    2: { titulo:'♉︎ Tauro · Segundo Decanato (Mercurio)', texto:'El segundo decanato de Tauro recibe la influencia de Mercurio, dando a esta tierra estable una mente más ágil y comunicativa de lo que se espera de Tauro. Combinas la persistencia y el sentido práctico del toro con una capacidad analítica y verbal que te hace especialmente efectivo en negociación, escritura o cualquier oficio que una manos y mente. Tu reto es no paralizarte por analizar en exceso lo que tu instinto ya sabe.' },
    3: { titulo:'♉︎ Tauro · Tercer Decanato (Saturno)', texto:'El tercer decanato de Tauro lleva la impronta de Saturno, añadiendo al signo una seriedad y una ambición constructiva que va más allá del confort. No te conformas con la estabilidad — la quieres edificada sobre algo duradero y con propósito. Eres el Tauro más disciplinado y orientado al largo plazo: puedes sacrificar placer presente por seguridad futura. Tu reto es no volverte demasiado rígido o severo contigo mismo en ese proceso.' },
  },
  geminis: {
    1: { titulo:'♊︎ Géminis · Primer Decanato (Mercurio)', texto:'El primer decanato de Géminis, regido por Mercurio en plena potencia, es el más veloz y versátil del zodíaco. Tu mente es un catálogo vivo: captas conexiones entre ideas donde otros ven fragmentos inconexos, y puedes hablar, escribir o enseñar con una facilidad que parece natural pero esconde un procesamiento constante. Necesitas estimulación intelectual para sentirte vivo. Tu reto es la profundidad — la curiosidad que todo lo toca a veces impide quedarse el tiempo suficiente para conocer algo de verdad.' },
    2: { titulo:'♊︎ Géminis · Segundo Decanato (Venus)', texto:'El segundo decanato de Géminis tiene a Venus como influencia, suavizando el filo mercurial con encanto, estética y un amor genuino por la conexión humana. Eres un Géminis con más corazón que el estereotipo: no solo te interesan las ideas sino las personas detrás de ellas. Tienes don para hacer que otros se sientan vistos e interesantes. Tu reto es la superficialidad afectiva — puedes enamorarte de muchas personas a la vez sin profundizar del todo en ninguna.' },
    3: { titulo:'♊︎ Géminis · Tercer Decanato (Urano)', texto:'El tercer decanato de Géminis lleva la energía de Urano, haciendo de este el Géminis más original, disruptivo e imprevisible. Tu mente no solo es rápida, es singular: piensas en ángulos que a los demás no se les ocurren y te aburres profundamente con lo convencional. Tienes visión de futuro y un instinto natural para detectar lo que está a punto de cambiar en el mundo. Tu reto es la constancia — las revoluciones que comienzas necesitan tierra firme para aterrizarse.' },
  },
  cancer: {
    1: { titulo:'♋︎ Cáncer · Primer Decanato (Luna)', texto:'El primer decanato de Cáncer, bajo el doble dominio lunar, es la expresión más pura e intensa del signo. Tu mundo interior es vasto, tu memoria emocional extraordinaria y tu capacidad de empatía casi sin límites. Sientes antes de pensar, y ese instinto emocional raramente te engaña. El hogar, la familia y los vínculos que se sienten como familia son tu centro de gravedad. Tu reto es no confundir cuidar con controlar, ni proteger con retener.' },
    2: { titulo:'♋︎ Cáncer · Segundo Decanato (Plutón)', texto:'El segundo decanato de Cáncer tiene a Plutón como subreino, añadiendo profundidad, intensidad y una dimensión transformadora a la sensibilidad canceriana. No solo sientes, sino que sientes en capas, y puedes percibir lo que hay debajo de lo que la gente muestra. Tienes una capacidad innata para los procesos de duelo, sanación y regeneración — tanto en ti como acompañando a otros. Tu reto es soltar el control emocional que ejerces como mecanismo de defensa.' },
    3: { titulo:'♋︎ Cáncer · Tercer Decanato (Neptuno)', texto:'El tercer decanato de Cáncer lleva la influencia de Neptuno, dando a esta agua ya profunda una dimensión mística y creativa poco común. Tienes una intuición que roza lo clarividente y una imaginación que puede construir mundos enteros. El arte, la música, la espiritualidad o el sueño son canales naturales para ti. Tu reto es distinguir entre intuición genuina y proyección emocional — y aprender a estar presente en una realidad que a veces sientes demasiado dura.' },
  },
  leo: {
    1: { titulo:'♌︎ Leo · Primer Decanato (Sol)', texto:'El primer decanato de Leo, regido por el Sol en plena expresión, encarna la esencia más luminosa y soberana del signo. Naciste para brillar con conciencia: no buscas atención por inseguridad sino porque tienes algo genuino que dar. Hay una generosidad natural en ti, una calidad solar que calienta a quienes te rodean. Líder por naturaleza, tu presencia organiza el espacio. Tu reto es aprender que la grandeza verdadera no necesita que los demás la confirmen constantemente.' },
    2: { titulo:'♌︎ Leo · Segundo Decanato (Júpiter)', texto:'El segundo decanato de Leo recibe a Júpiter, amplificando el fuego leonino con visión, filosofía y una generosidad que puede volverse legendaria. Eres el Leo más expansivo y optimista: crees en los demás con una fe que a veces supera la que ellos tienen en sí mismos. Tienes talento para inspirar y para crear oportunidades donde otros ven límites. Tu reto es el exceso — en promesas, en gastos, en protagonismo — y aprender a medir sin perder la magnanimidad.' },
    3: { titulo:'♌︎ Leo · Tercer Decanato (Marte)', texto:'El tercer decanato de Leo lleva la energía de Marte, añadiendo al fuego solar una determinación combativa y una voluntad de hierro. No solo quieres brillar, quieres conquistar: metas, desafíos, proyectos que pongan a prueba tu capacidad. Tienes una energía casi inagotable cuando algo te motiva, y una resistencia ante la adversidad que impresiona. Tu reto es el orgullo herido — cuando Marte y Leo se unen en el ego, perder puede sentirse inaceptable.' },
  },
  virgo: {
    1: { titulo:'♍︎ Virgo · Primer Decanato (Mercurio)', texto:'El primer decanato de Virgo, bajo el doble dominio mercurial, es el más analítico y preciso del zodíaco de tierra. Tu mente disecciona la realidad con una finura extraordinaria: ves los errores, los detalles que faltan, los procesos que pueden mejorarse. Eres el primero en llegar con una solución práctica cuando algo no funciona. Tu servicio a los demás nace de un amor genuino por la excelencia. Tu reto es el perfeccionismo que te paraliza, y la crítica interna que nunca descansa.' },
    2: { titulo:'♍︎ Virgo · Segundo Decanato (Saturno)', texto:'El segundo decanato de Virgo lleva la impronta de Saturno, dando a esta tierra analítica una seriedad, responsabilidad y orientación al deber poco comunes. Eres el Virgo más disciplinado y estructurado: cumples lo que prometes, construyes a largo plazo y tomas en serio lo que para otros es opcional. Hay una madurez natural en ti que genera confianza. Tu reto es la rigidez — cuando las reglas que te has impuesto se vuelven una jaula en lugar de un andamiaje.' },
    3: { titulo:'♍︎ Virgo · Tercer Decanato (Venus)', texto:'El tercer decanato de Virgo recibe la influencia de Venus, suavizando el rigor virguiano con sensibilidad estética y una necesidad de armonía que no siempre se espera de este signo. Combinas el ojo crítico de Virgo con un sentido artístico refinado: puedes crear belleza con precisión, o precisión con belleza. En las relaciones eres más afectuoso y receptivo que el Virgo promedio. Tu reto es aceptar la imperfección — en el mundo, en los demás y sobre todo en ti mismo.' },
  },
  libra: {
    1: { titulo:'♎︎ Libra · Primer Decanato (Venus)', texto:'El primer decanato de Libra, bajo el doble dominio venusino, es la expresión más pura del equilibrio, la belleza y la diplomacia. Tienes un don natural para crear armonía donde hay tensión, y una sensibilidad estética que convierte cualquier entorno en algo más bello. En las relaciones eres atento, considerado y genuinamente interesado en el bienestar del otro. Tu reto es la indecisión que nace de querer que todo el mundo esté bien — a veces olvidando lo que tú necesitas.' },
    2: { titulo:'♎︎ Libra · Segundo Decanato (Urano)', texto:'El segundo decanato de Libra lleva la energía de Urano, añadiendo al equilibrio venusino una vena reformista, original e independiente que sorprende. Eres el Libra más inconformista: buscas la justicia no solo en las relaciones personales sino en sistemas más amplios, y puedes ser un agente de cambio social genuino. Tu sentido de la equidad tiene una dimensión intelectual y progresista. Tu reto es conciliar tu amor por la libertad con tu igualmente profunda necesidad de conexión.' },
    3: { titulo:'♎︎ Libra · Tercer Decanato (Mercurio)', texto:'El tercer decanato de Libra tiene a Mercurio como influencia, dando a esta balanza una elocuencia y una capacidad negociadora excepcionales. Sabes hablar, persuadir y argumentar con una elegancia que desactiva conflictos antes de que escalen. Eres el mediador por excelencia: ves todos los ángulos y puedes representar cualquier posición con justicia. Tu reto es usar esa misma elocuencia para decir lo que piensas con honestidad, no solo para mantener la paz.' },
  },
  escorpio: {
    1: { titulo:'♏︎ Escorpio · Primer Decanato (Plutón/Marte)', texto:'El primer decanato de Escorpio, bajo la influencia combinada de Plutón y Marte, es el más intenso y transformador del zodíaco. Tienes una profundidad psicológica innata y una capacidad de ver debajo de las superficies que puede resultar intimidante para quienes tienen algo que ocultar. No temes la oscuridad — la conoces como un territorio familiar. Tu poder de regeneración es extraordinario: puedes renacer de experiencias que destruirían a otros. Tu reto es el control y la desconfianza que usa como escudo.' },
    2: { titulo:'♏︎ Escorpio · Segundo Decanato (Neptuno)', texto:'El segundo decanato de Escorpio recibe a Neptuno, añadiendo a la intensidad escorpiana una dimensión mística, intuitiva y artística de gran profundidad. Sientes las corrientes emocionales y espirituales que otros ni perciben, y tienes un acceso natural a dimensiones de la experiencia humana que van más allá de lo racional. El arte, la espiritualidad o la psicología pueden ser vehículos poderosos para ti. Tu reto es distinguir entre intuición y ilusión, y no perderte en las profundidades que explorad.' },
    3: { titulo:'♏︎ Escorpio · Tercer Decanato (Luna)', texto:'El tercer decanato de Escorpio lleva la impronta lunar, añadiendo a este signo de agua una sensibilidad emocional y una memoria afectiva de enorme riqueza. Sientes con una intensidad que puede ser tanto una fuente de profundidad como de sufrimiento, y tienes una capacidad de apego que va más allá de lo que muestras externamente. Las relaciones son para ti transformadoras por definición. Tu reto es soltar los vínculos que ya cumplieron su función, y confiar en que la vulnerabilidad no es debilidad.' },
  },
  sagitario: {
    1: { titulo:'♐︎ Sagitario · Primer Decanato (Júpiter)', texto:'El primer decanato de Sagitario, bajo el doble dominio jupiterino, es la expresión más expansiva, libre y filosófica del signo. Tienes una sed de horizonte que ningún destino termina de saciar, y una fe en la vida que puede atravesar circunstancias que doblarían a cualquiera. Tu entusiasmo es contagioso, tu visión generosa y tu amor por el conocimiento genuino. Tu reto es el exceso en todas sus formas — y aprender que la profundidad también es una forma de expansión.' },
    2: { titulo:'♐︎ Sagitario · Segundo Decanato (Marte)', texto:'El segundo decanato de Sagitario lleva la energía de Marte, añadiendo al fuego jupiterino una determinación y una combatividad que convierte las visiones en acciones. No solo sueñas grandes — actúas en grande. Tienes una energía casi atlética para perseguir lo que crees, y no te amedrentan los obstáculos que se interponen en tu camino. Tu reto es la impulsividad — cuando Marte y Sagitario se unen sin freno, la sinceridad puede volverse descuido y la iniciativa, temeridad.' },
    3: { titulo:'♐︎ Sagitario · Tercer Decanato (Sol)', texto:'El tercer decanato de Sagitario recibe la influencia del Sol, iluminando el fuego sagitariano con una conciencia de propósito y una necesidad de dejar legado. Eres el Sagitario más orientado al significado: no solo buscas la aventura sino la sabiduría que se extrae de ella. Tienes una calidad de guía o maestro natural que atrae a quienes buscan dirección. Tu reto es no convertir tu filosofía en dogma, ni tu visión del mundo en la única posible.' },
  },
  capricornio: {
    1: { titulo:'♑︎ Capricornio · Primer Decanato (Saturno)', texto:'El primer decanato de Capricornio, bajo el doble dominio saturnino, es la expresión más pura de la ambición disciplinada y la construcción paciente. Sabes de manera casi instintiva que los resultados duraderos se construyen paso a paso, y tienes la templanza para no precipitarte. Hay una madurez innata en ti, una seriedad que a veces hace que parezcas mayor de lo que eres. Tu reto es permitirte disfrutar el camino además de llegar a la cima, y soltar la carga de la responsabilidad autoimpuesta.' },
    2: { titulo:'♑︎ Capricornio · Segundo Decanato (Venus)', texto:'El segundo decanato de Capricornio recibe la influencia de Venus, suavizando la dureza saturnina con sensibilidad estética y una capacidad de conexión afectiva más visible que la del Capricornio típico. Combinas la ambición y la disciplina del signo con un gusto refinado y la necesidad de construir algo bello además de sólido. En las relaciones eres más afectuoso y expresivo de lo que tu fachada sugiere. Tu reto es no usar el éxito como sustituto del amor.' },
    3: { titulo:'♑︎ Capricornio · Tercer Decanato (Mercurio)', texto:'El tercer decanato de Capricornio lleva la impronta de Mercurio, añadiendo a la tierra capricorniana una inteligencia estratégica y una capacidad comunicativa que potencian enormemente su eficacia. Eres el Capricornio más analítico y adaptable: puedes planificar con precisión y también ajustar el plan cuando la realidad lo requiere. Tienes talento para la gestión, la estrategia y cualquier campo donde pensar y construir se combinen. Tu reto es no reducir todo a utilidad y eficiencia.' },
  },
  acuario: {
    1: { titulo:'♒︎ Acuario · Primer Decanato (Urano/Saturno)', texto:'El primer decanato de Acuario, bajo la influencia combinada de Urano y Saturno, une la visión revolucionaria con la capacidad de estructurarla. Eres el reformador más efectivo del zodíaco: no solo ves lo que necesita cambiar, sino que tienes la disciplina para construir la alternativa. Tu pensamiento es genuinamente original y tu compromiso con lo colectivo, profundo. Tu reto es la frialdad emocional que puede acompañar tanta racionalidad, y aprender que los cambios también ocurren en el interior.' },
    2: { titulo:'♒︎ Acuario · Segundo Decanato (Mercurio)', texto:'El segundo decanato de Acuario tiene a Mercurio como subreino, añadiendo al aire acuariano una agilidad mental y una capacidad comunicativa extraordinarias. Eres el pensador más brillante y articulado del signo: no solo tienes ideas originales, sino que puedes transmitirlas de manera que otros las entiendan y adopten. Hay algo del inventor y del divulgador en ti. Tu reto es no quedarte en el plano de las ideas y llevar tus visiones al terreno de lo concreto.' },
    3: { titulo:'♒︎ Acuario · Tercer Decanato (Venus)', texto:'El tercer decanato de Acuario recibe la influencia de Venus, humanizando el distanciamiento acuariano con una calidez y un amor por la conexión que equilibran la tendencia al intelecto puro. Eres el Acuario más cercano y afectuoso: te importa la humanidad no como concepto abstracto sino como las personas concretas que tienes delante. Tienes un talento especial para crear comunidad y hacer que la gente se sienta incluida. Tu reto es abrirte a la intimidad real, no solo a la camaradería.' },
  },
  piscis: {
    1: { titulo:'♓︎ Piscis · Primer Decanato (Neptuno/Júpiter)', texto:'El primer decanato de Piscis, bajo la influencia de Neptuno y Júpiter, es el más místico, empático y creativo del zodíaco. Tu porosidad con el mundo emocional y espiritual que te rodea puede ser tu mayor don y tu mayor vulnerabilidad. Sientes lo que otros sienten antes de que lo expresen, y tienes acceso a dimensiones de la experiencia que la mayoría ni sospecha. El arte, la espiritualidad y la sanación son caminos naturales para ti. Tu reto es mantener tus límites sin perder tu apertura.' },
    2: { titulo:'♓︎ Piscis · Segundo Decanato (Luna)', texto:'El segundo decanato de Piscis lleva la impronta lunar, añadiendo a las aguas piscianas una profundidad emocional y una memoria afectiva de extraordinaria riqueza. Sientes todo con una intensidad que puede ser abrumadora, y tienes una capacidad de nutrir y contener a los demás que los hace sentir verdaderamente sostenidos. Hay algo del sanador y del guardián emocional en ti. Tu reto es no absorber el dolor ajeno como propio, y aprender a recibir el cuidado que tan naturalmente das.' },
    3: { titulo:'♓︎ Piscis · Tercer Decanato (Plutón)', texto:'El tercer decanato de Piscis recibe la energía de Plutón, dando a este signo de agua una profundidad transformadora y una capacidad de regeneración poco comunes. No solo sientes, sino que transformas lo que sientes en comprensión, en arte o en sabiduría. Tienes acceso a las raíces más profundas de la psique — la tuya y la de quienes te rodean. Tu reto es soltar el peso de lo que has acumulado emocionalmente, y confiar en que el vacío que deja es necesario para lo que viene.' },
  },
};

// ════════════════════════════════════════════════════════════════════
// DATOS PARA mensajes_astrologicos.js
// Copiar todo este bloque al final del archivo mensajes_astrologicos.js
// ════════════════════════════════════════════════════════════════════

// ── 1. PERSONALIDAD — Sol por signo (renderPersResult) ──
window._PERS_SOL = {
    aries:       'El Sol en Aries define una identidad construida sobre la acción y el impulso. Aries solar es el pionero del zodiaco: entra al mundo con la certeza de que él debe ir primero, abrir caminos y enfrentar lo que nadie se ha atrevido aún. Su esencia es el fuego en estado puro —intenso, inmediato y sin filtro. La energía que irradia es contagiosa, su presencia difícil de ignorar. Su mayor desafío es aprender que la fuerza también se expresa en la paciencia, y que los mejores líderes saben cuándo esperar. Cuando integra esto, se convierte en una fuerza de la naturaleza capaz de transformar el entorno con su sola presencia.',
    tauro:       'El Sol en Tauro define una identidad anclada en lo concreto, lo sensorial y lo duradero. Tauro solar construye su mundo con lentitud y solidez —nada que valga la pena llega rápido, y él lo sabe mejor que nadie. Su presencia irradia calma, confianza y una profunda conexión con el placer de existir: la buena comida, la naturaleza, la belleza tangible. Su mayor desafío es la rigidez —cuando se aferra demasiado a lo conocido puede perder oportunidades de crecimiento. Cuando fluye con el cambio sin perder su centro, se convierte en uno de los signos más plenos y realizados del zodiaco.',
    geminis:     'El Sol en Géminis define una identidad construida sobre la curiosidad y la capacidad de conectar ideas que nadie más había relacionado. Géminis solar existe en el movimiento perpetuo de la mente: necesita estímulo constante, conversación, novedad. Su presencia irradia ingenio, adaptabilidad y un humor que desestabiliza las certezas. Su mayor desafío es la superficialidad —la tendencia a tocar todo sin profundizar en nada. Cuando aprende a comprometerse con algo más allá del primer entusiasmo, descubre que su mente brillante puede crear obras de profundidad real.',
    cancer:      'El Sol en Cáncer define una identidad profundamente ligada al mundo emocional, la familia y la memoria. Cáncer solar construye desde adentro hacia afuera: primero necesita sentirse seguro, protegido, amado —y desde ahí puede darlo todo. Su presencia irradia calidez, intuición y una capacidad de cuidado que pocos signos igualan. Su mayor desafío es el miedo a la vulnerabilidad —la tendencia a protegerse tanto que nadie puede realmente entrar. Cuando aprende que ser visto también es una forma de valentía, se convierte en uno de los seres más profundos y nutritivos del zodiaco.',
    leo:         'El Sol en Leo define una identidad construida sobre la autoexpresión, la creatividad y el liderazgo natural. Leo solar nació sabiendo que tiene algo especial que dar al mundo —y su trabajo vital es descubrir exactamente qué es eso y ofrecerlo con generosidad. Su presencia irradia magnetismo, calidez y una confianza que puede elevar a todos los que están cerca. Su mayor desafío es el ego no integrado —la necesidad de reconocimiento que se convierte en dependencia. Cuando aprende que su luz es más brillante cuando ilumina a otros, se convierte en una fuerza de inspiración genuina.',
    virgo:       'El Sol en Virgo define una identidad construida sobre el discernimiento, el servicio y la búsqueda constante de mejora. Virgo solar tiene un don innato para ver lo que falla, lo que puede perfeccionarse, lo que está fuera de lugar —y la paciencia para trabajarlo. Su presencia irradia precisión, competencia y una humildad real que inspira confianza. Su mayor desafío es el perfeccionismo que paraliza —la crítica interna que nunca deja nada por terminado. Cuando aprende a honrar lo que ya es suficiente, descubre que su capacidad de análisis es uno de los dones más valiosos del zodiaco.',
    libra:       'El Sol en Libra define una identidad construida sobre la búsqueda de armonía, belleza y justicia relacional. Libra solar existe en relación —necesita el otro para conocerse a sí mismo, y tiene el don de crear espacios donde todos se sienten escuchados y valorados. Su presencia irradia elegancia, diplomacia y un sentido estético que transforma lo ordinario en bello. Su mayor desafío es la indecisión y la pérdida de sí mismo en el intento de complacer a todos. Cuando aprende a honrar sus propias necesidades con la misma atención que da a las ajenas, se convierte en uno de los signos más equilibrados y sabios del zodiaco.',
    escorpio:    'El Sol en Escorpio define una identidad construida sobre la profundidad, la transformación y el poder de mirar donde otros no se atreven. Escorpio solar existe en las capas no visibles de la realidad —lo que se esconde, lo que duele, lo que puede morir y renacer. Su presencia irradia intensidad, misterio y una percepción que pocos pueden engañar. Su mayor desafío es el control y la desconfianza —la tendencia a retener poder como forma de protección. Cuando aprende a soltar y confiar, se convierte en el alquimista del zodiaco: capaz de transformar el dolor más oscuro en sabiduría real.',
    sagitario:   'El Sol en Sagitario define una identidad construida sobre la búsqueda de sentido, la expansión y la libertad como valor supremo. Sagitario solar es el filósofo y el aventurero del zodiaco —necesita horizontes siempre más amplios, ideas que lo hagan crecer, experiencias que prueben que el mundo es más grande de lo que imagina. Su presencia irradia optimismo, entusiasmo y una fe en la vida que resulta contagiosa. Su mayor desafío es la irresponsabilidad —la tendencia a escapar cuando la realidad pide compromiso. Cuando integra la disciplina sin perder su espíritu libre, se convierte en un maestro genuino.',
    capricornio: 'El Sol en Capricornio define una identidad construida sobre la ambición, la disciplina y el respeto profundo por el tiempo. Capricornio solar sabe que nada importante llega sin trabajo, y tiene la voluntad de hacer lo que sea necesario para construir algo que dure. Su presencia irradia madurez, solidez y una autoridad ganada con hechos, no con palabras. Su mayor desafío es la frialdad emocional —la tendencia a desconectarse de sus propias necesidades afectivas en nombre de la meta. Cuando aprende que la vulnerabilidad no es debilidad sino profundidad, se convierte en uno de los pilares más confiables del zodiaco.',
    acuario:     'El Sol en Acuario define una identidad construida sobre la originalidad, la visión de futuro y la necesidad de romper esquemas. Acuario solar existe siempre un paso adelante de su tiempo —ve lo que otros aún no ven y se siente incómodo en cualquier estructura que limite su libertad de pensar diferente. Su presencia irradia independencia, brillantez intelectual y una humanidad genuina que lo hace querer cambiar el mundo. Su mayor desafío es la desconexión emocional —la tendencia a vivir en las ideas y alejarse de lo humano y cercano. Cuando integra el corazón con la mente, su visión se vuelve transformadora de verdad.',
    piscis:      'El Sol en Piscis define una identidad construida sobre la sensibilidad, la compasión y una conexión con lo invisible que pocos comprenden. Piscis solar existe entre mundos —el real y el que imagina, el propio y el ajeno, el consciente y el que sueña. Su presencia irradia empatía, creatividad y una profundidad espiritual que puede tocar el alma de quienes lo rodean. Su mayor desafío es la disolución del yo —la tendencia a perderse en el otro, en la fantasía o en el escape. Cuando aprende a sostener sus propios límites sin perder su sensibilidad, se convierte en uno de los seres más profundamente humanos del zodiaco.',
  };


// ── 2. PERSONALIDAD — Luna por signo (renderPersResult) ──
window._PERS_LUNA = {
    aries:       'La Luna en Aries describe un mundo emocional impulsivo, reactivo y de gran intensidad inmediata. Quien tiene esta Luna siente fuerte y rápido —las emociones llegan como llama y se expresan sin filtro. Necesita acción para procesar lo que siente: no puede quedarse quieto cuando algo lo mueve por dentro. Su primer instinto ante el dolor es la lucha, y ante la alegría, el movimiento. Su mayor desafío es la impaciencia emocional —la dificultad para sostener las emociones más lentas, como la tristeza o la espera. Cuando aprende a darle tiempo a lo que siente sin huir de ello, descubre una profundidad emocional que sorprende incluso a quienes lo conocen bien.',
    tauro:       'La Luna en Tauro es considerada la Luna más cómoda del zodiaco por su estabilidad y sensualidad natural. Quien la tiene necesita seguridad material y emocional para estar bien —la rutina, el hogar cálido, los placeres sensoriales son su alimento del alma. Sus emociones son profundas, constantes y difíciles de mover: no cambia de estado de ánimo con facilidad, pero cuando algo lo desequilibra, puede costar mucho volver al centro. Su mayor desafío es la resistencia al cambio emocional. Cuando aprende a fluir, descubre que su estabilidad puede ser un ancla poderosa para todos los que lo rodean.',
    geminis:     'La Luna en Géminis describe un mundo emocional que necesita ser comprendido para poder ser sentido. Quien la tiene procesa sus emociones a través del lenguaje —hablando, escribiendo, analizando. La incertidumbre emocional lo inquieta y busca explicaciones racionales para lo que siente. Necesita variedad y estimulación mental constante para sentirse vivo; el aburrimiento emocional es su mayor enemigo. Su mayor desafío es la superficialidad afectiva —la dificultad para quedarse en la profundidad cuando esta incomoda. Cuando aprende a tolerar lo que no puede explicar, su inteligencia emocional se vuelve uno de sus mayores dones.',
    cancer:      'La Luna en Cáncer está en su domicilio —el lugar donde más cómoda se siente. Quien la tiene posee una sensibilidad emocional profunda y una memoria afectiva extraordinaria: recuerda cada detalle de cómo se sintió en cada momento importante de su vida. Necesita un hogar emocionalmente seguro para florecer, y tiene un instinto protector hacia quienes ama que puede rozar la sobreprotección. Su mayor desafío es la tendencia a quedar atrapado en el pasado emocional o en el humor cambiante como la marea. Cuando aprende a nutrir su mundo interior sin descuidar el presente, es capaz de una profundidad emocional sin igual.',
    leo:         'La Luna en Leo describe un mundo emocional que necesita ser visto, reconocido y celebrado. Quien la tiene siente con intensidad dramática —las alegrías son grandes fiestas internas y los dolores, tragedias genuinas. Necesita afecto expresivo y constante: no le basta que lo quieran, necesita que se lo demuestren. Tiene una generosidad emocional notable cuando se siente amado y seguro. Su mayor desafío es el orgullo herido —la dificultad para mostrar vulnerabilidad cuando el ego está en juego. Cuando aprende que pedir amor no es debilidad sino valentía, su calor emocional se convierte en una de sus cualidades más poderosas.',
    virgo:       'La Luna en Virgo describe un mundo emocional que se procesa a través del análisis y el orden. Quien la tiene tiende a intelectualizar lo que siente —necesita entender sus emociones para poder aceptarlas. Encuentra calma en la rutina, en el trabajo bien hecho, en ayudar a otros de manera concreta. Su mayor desafío es la hipercrítica interna —una voz que analiza cada sentimiento y lo juzga como insuficiente o irracional. Cuando aprende a tratarse con la misma compasión que ofrece a los demás, su capacidad de análisis emocional se convierte en una herramienta de crecimiento genuino.',
    libra:       'La Luna en Libra describe un mundo emocional que necesita armonía relacional para sentirse en equilibrio. Quien la tiene se angustia ante el conflicto, busca la justicia afectiva y tiene una tendencia natural a considerar las emociones de todos antes que las propias. Su bienestar está profundamente ligado a la calidad de sus vínculos. Tiene el don de crear paz donde hay tensión, pero puede perder de vista sus propias necesidades en el proceso. Su mayor desafío es el miedo a desequilibrar al otro al expresar lo que realmente siente. Cuando aprende que la honestidad emocional no destruye los vínculos sino que los profundiza, encuentra el equilibrio que tanto busca.',
    escorpio:    'La Luna en Escorpio describe un mundo emocional de una intensidad y profundidad poco comunes. Quien la tiene siente en capas —lo que muestra es solo la superficie de lo que ocurre dentro. Tiene una memoria emocional afilada y una dificultad real para perdonar las traiciones, porque su mundo afectivo está construido sobre la confianza total o la desconfianza absoluta. Necesita vínculos de profundidad real; la superficialidad afectiva lo agota. Su mayor desafío es el control y la posesividad emocional. Cuando aprende a soltar lo que ya no sirve, su capacidad de transformación emocional es de las más poderosas del zodiaco.',
    sagitario:   'La Luna en Sagitario describe un mundo emocional que necesita libertad y expansión para respirar. Quien la tiene siente con optimismo y generosidad, pero se ahoga en los vínculos que lo limitan o en los ambientes emocionalmente pesados. Necesita que sus relaciones tengan espacio para crecer, explorar y evolucionar. Tiene una alegría emocional genuina y contagiosa cuando está en su elemento. Su mayor desafío es la evasión —la tendencia a huir del dolor emocional buscando el próximo horizonte. Cuando aprende a sentarse con lo incómodo en lugar de escapar, descubre que sus emociones también pueden ser maestras.',
    capricornio: 'La Luna en Capricornio describe un mundo emocional contenido, estructurado y profundamente ligado a la responsabilidad. Quien la tiene tiende a reprimir lo que siente bajo la lógica de que las emociones son un lujo o una debilidad. Encuentra seguridad en la competencia, en el control y en tener todo bajo orden. Su mayor desafío es la desconexión afectiva —la dificultad para dejarse querer o para expresar lo que necesita. Con el tiempo, aprende que la vulnerabilidad no contradice su fortaleza sino que la completa, y que el amor también necesita ser recibido para florecer.',
    acuario:     'La Luna en Acuario describe un mundo emocional que observa más que siente —o que al menos así parece desde afuera. Quien la tiene tiene una relación con sus propias emociones marcada por la distancia: las analiza, las categoriza, las comparte de forma intelectual. Necesita independencia emocional como el aire: los vínculos demasiado fusionales lo asfixian. Tiene una empatía genuina hacia la humanidad en abstracto pero puede tener dificultades con la intimidad individual concreta. Su mayor desafío es bajar del plano intelectual al emocional sin sentir que pierde el control.',
    piscis:      'La Luna en Piscis describe un mundo emocional de una porosidad extraordinaria. Quien la tiene absorbe el campo emocional de quienes lo rodean casi sin darse cuenta —puede entrar a un lugar sintiéndose bien y salir cargando el dolor de otros. Su sensibilidad es tan fina que la música, el arte o un paisaje pueden moverlo a las lágrimas. Su mayor desafío es la falta de límites emocionales —la dificultad para distinguir qué es suyo y qué es del otro. Cuando aprende a proteger su mundo interior sin cerrarlo, su capacidad empática se convierte en uno de los dones espirituales más profundos del zodiaco.',
  };


// ── 3. PERSONALIDAD — Ascendente por signo (renderPersResult) ──
window._PERS_ASC = {
    aries:       'El Ascendente en Aries define la manera en que el mundo percibe a esta persona: directa, enérgica, inmediata. Antes de que pueda decir una palabra, su presencia ya comunicó algo —hay una vitalidad en su forma de entrar, de mirar, de moverse que resulta difícil de ignorar. Con este ascendente, la vida tiende a comenzar con impulsos y decisiones rápidas; el primer instinto es actuar. Puede parecer más impulsivo o combativo de lo que realmente es, porque el cuerpo comunica fuego incluso cuando el interior es más complejo. Su mayor desafío es aprender que no todas las batallas necesitan ser peleadas, y que la suavidad también puede abrirle puertas que la fuerza no alcanza.',
    tauro:       'El Ascendente en Tauro define una presencia que el mundo percibe como calmante, confiable y sólida. Hay algo en esta persona que hace que los demás se sientan seguros a su lado —una estabilidad que se nota antes de conocerla. Tiende a moverse con lentitud deliberada, hablar con cuidado, y crear ambientes donde todo tiene su lugar. El mundo la percibe como sensual, paciente y con buen gusto. Su mayor desafío con este ascendente es la resistencia al cambio que puede generar en su imagen: a veces es percibida como inflexible o demasiado apegada a sus costumbres antes de que puedan ver su profundidad real.',
    geminis:     'El Ascendente en Géminis define una presencia que el mundo percibe como ágil, curiosa y socialmente brillante. Esta persona tiene el don de adaptarse a cualquier ambiente y encontrar algo interesante que decir en cualquier situación. Su imagen es la de alguien inteligente, accesible y divertido. Puede hablar con casi cualquiera y hacer que se sienta escuchado. Su mayor desafío con este ascendente es que el mundo puede subestimarla —la ligereza de su imagen puede ocultar la profundidad real de su interior. Con el tiempo, aprende a usar su don comunicativo para mostrar también sus capas más complejas.',
    cancer:      'El Ascendente en Cáncer define una presencia que el mundo percibe como cálida, cercana y emocionalmente accesible. Hay algo en esta persona que invita a la confianza —la gente tiende a contarle sus problemas casi sin conocerla, porque su presencia comunica cuidado y comprensión antes de que pueda decir una palabra. Su imagen está ligada a la ternura, el hogar y la protección. Su mayor desafío con este ascendente es la permeabilidad —absorbe el ambiente emocional de donde está con facilidad, y puede verse afectada por entornos negativos más de lo que le conviene. Cuando aprende a proteger su sensibilidad sin cerrarla, su presencia se convierte en un refugio genuino para quienes la rodean.',
    leo:         'El Ascendente en Leo define una presencia que el mundo percibe como magnética, carismática y con una autoridad natural que no necesita imponerse. Esta persona entra a un lugar y algo cambia —hay una energía solar en su forma de ser que atrae miradas sin que ella lo busque necesariamente. El mundo la percibe como confiada, generosa y con una presencia escénica natural. Su mayor desafío con este ascendente es la presión de mantener la imagen: puede sentir que siempre debe estar "brillando" aunque por dentro no lo sienta. Cuando aprende que puede mostrar su vulnerabilidad sin perder su luz, su magnetismo se vuelve aún más real y profundo.',
    virgo:       'El Ascendente en Virgo define una presencia que el mundo percibe como discreta, competente y cuidadosa. Esta persona no entra haciendo ruido —entra observando, analizando, asegurándose de entender el terreno antes de actuar. Su imagen es la de alguien en quien se puede confiar para hacer las cosas bien, con atención al detalle y sin drama innecesario. El mundo la percibe como inteligente, servicial y con los pies en la tierra. Su mayor desafío con este ascendente es que puede ser juzgada como fría o distante antes de que la conozcan, cuando en realidad su calidez simplemente toma más tiempo en mostrarse.',
    libra:       'El Ascendente en Libra define una presencia que el mundo percibe como elegante, armoniosa y naturalmente diplomática. Hay algo en esta persona que hace que los ambientes donde está se vuelvan más agradables —una gracia social que parece innata. El mundo la percibe como justa, encantadora y con buen gusto. Tiene el don de hacer que cada persona a la que habla sienta que es la más importante de la sala. Su mayor desafío con este ascendente es que puede parecer indecisa o superficial antes de que la conozcan mejor, cuando en realidad su aparente ligereza esconde una mente profundamente reflexiva.',
    escorpio:    'El Ascendente en Escorpio define una presencia que el mundo percibe como intensa, misteriosa y con una profundidad que no puede ignorarse. Esta persona entra a un lugar y algo se siente —hay una energía invisible pero palpable en su forma de ser que genera fascinación y a veces incomodidad. El mundo la percibe como poderosa, magnética y difícil de engañar. Su mirada parece ver más de lo que debería. Su mayor desafío con este ascendente es el aislamiento —la intensidad que proyecta puede alejar a quienes no están preparados para esa profundidad, aunque ella solo quería conectar.',
    sagitario:   'El Ascendente en Sagitario define una presencia que el mundo percibe como libre, entusiasta y abierta al mundo. Esta persona irradia una energía de explorador —siempre parece que está a punto de emprender algo nuevo, de ir a algún lugar interesante, de descubrir algo que vale la pena compartir. El mundo la percibe como optimista, filosófica y genuinamente interesada en aprender de los demás. Su mayor desafío con este ascendente es que puede parecer exagerada o poco confiable en su constancia, cuando en realidad su entusiasmo es genuino —simplemente necesita libertad para expresarse.',
    capricornio: 'El Ascendente en Capricornio define una presencia que el mundo percibe como seria, madura y con una autoridad natural ganada con hechos. Esta persona puede parecer más mayor de lo que es —hay algo en su forma de moverse y hablar que comunica experiencia y responsabilidad antes de tiempo. El mundo la percibe como confiable, ambiciosa y con una solidez que da seguridad. Su mayor desafío con este ascendente es la imagen de frialdad que puede proyectar —la gente puede tardarse en ver su humor, su ternura y su lealtad profunda porque el exterior parece siempre tan controlado.',
    acuario:     'El Ascendente en Acuario define una presencia que el mundo percibe como original, independiente y difícil de clasificar. Esta persona tiene algo que la hace diferente de todos los demás en la sala —no necesariamente en lo visual, sino en una energía de unicidad que es palpable. El mundo la percibe como inteligente, poco convencional y con ideas propias que no negocia fácilmente. Su mayor desafío con este ascendente es la percepción de distancia —puede parecer fría o desinteresada cuando en realidad simplemente opera desde una frecuencia diferente a la mayoría.',
    piscis:      'El Ascendente en Piscis define una presencia que el mundo percibe como suave, etérea y emocionalmente porosa. Hay algo en esta persona que parece no del todo anclado al mundo concreto —una calidad de ensueño en su mirada, una sensibilidad en su presencia que hace que los demás se sientan vistos emocionalmente. El mundo la percibe como empática, artística y profundamente intuitiva. Su mayor desafío con este ascendente es que puede ser percibida como poco confiable o difusa, cuando en realidad su forma de navegar el mundo es simplemente más fluida y menos lineal que la de la mayoría.',
  };

// ══════════════════════════════════════════════════════════════
// TEXTOS DE SÍNTESIS DE PERSONALIDAD — v2
// Pegar al final de mensajes_astrologicos.js (reemplaza la versión anterior)
// Los tres párrafos (Sol, Luna, Asc) se muestran juntos como
// síntesis fluida en "Tu Personalidad" y en Carta Natal.
// Tuteo formal, sin prefijos identificadores de signo.
// ══════════════════════════════════════════════════════════════

window._SINT_SOL = {
  aries:
    "Hay en ti una energía que no sabe esperar porque siente que el momento es siempre ahora. Llegas al mundo con el impulso de iniciar, de encender lo que estaba quieto, de abrir caminos antes de que estén trazados. Esa urgencia es tu mayor don —y también el territorio donde más tienes que aprender a soltar el control.",
  tauro:
    "Construyes lento, pero lo que construyes dura. Tienes una relación profunda con lo concreto —el cuerpo, la tierra, la belleza que se puede tocar— y una voluntad que no cede cuando algo realmente importa. Tu presencia tiene peso, y eso es algo que pocas personas logran.",
  geminis:
    "Tu mente capta conexiones donde otros ven fragmentos, y necesita estímulo constante para sentirse viva. La curiosidad no es un rasgo que tienes —es tu forma de estar en el mundo. Eso te da una versatilidad que desarma, aunque a veces te cuesta saber cuál de todas tus versiones es la más tuya.",
  cancer:
    "Sientes todo con una profundidad que el mundo no siempre comprende, y llevas dentro un archivo de emociones, vínculos y lugares que te forman en cada decisión. La memoria emocional es tu mapa. A través de ella sabes quién eres, dónde perteneces y qué merece ser protegido.",
  leo:
    "Tienes una necesidad genuina de ser visto y de brillar, no por vanidad sino porque sientes que tienes algo real para dar. Cuando encuentras tu escenario, todo lo que eres se vuelve generoso. El desafío no es brillar —eso lo haces de manera natural— sino aprender a hacerlo sin necesitar la validación de los demás.",
  virgo:
    "Ves los detalles que otros pasan por alto y tienes una necesidad profunda de que las cosas funcionen bien, de que el caos tenga orden. Tu perfeccionismo no es rigidez —es amor expresado en forma de cuidado. El reto está en aprender a dirigir esa mirada también hacia ti, con la misma compasión que aplicas a los demás.",
  libra:
    "Buscas la armonía no como algo estático sino como algo que se negocia constantemente. Tienes una inteligencia relacional que lee el espacio entre las personas y sabe cómo acercarse sin invadir. Esa capacidad de equilibrio es tu herramienta más poderosa, aunque a veces el miedo al conflicto te lleva a posponer lo que necesita ser dicho.",
  escorpio:
    "No te conformas con la superficie de nada —las personas, las ideas, las situaciones— y esa necesidad de ir al núcleo es lo que te hace transformador. Lo que tocas cambia, y tú también cambias con ello. Aprender a confiar en ese proceso, sin intentar controlarlo todo, es el trabajo más profundo de tu vida.",
  sagitario:
    "Necesitas horizontes, preguntas sin respuesta fácil y libertad para moverte hacia donde apunta tu curiosidad más profunda. La vida sin significado te resulta insoportable. Esa búsqueda constante te lleva lejos —en distancia, en ideas, en experiencias— y en ese camino encuentras lo que realmente eres.",
  capricornio:
    "Tienes una relación seria con el tiempo: sabes que lo importante se logra con constancia y que los atajos suelen costar más de lo que ahorran. Hay en ti una ambición que no es codicia sino la necesidad de construir algo sólido, algo que tenga sentido mucho después de que hayas pasado.",
  acuario:
    "Piensas diferente y lo sabes, y esa diferencia no es un defecto sino la fuente de todo lo que tienes para aportar. Tu mente conecta lo que parece inconexo y anticipa lo que otros aún no ven. El desafío está en no quedarte tan afuera del mundo que termines hablando solo —porque lo que ves necesita ser escuchado.",
  piscis:
    "Absorbes el mundo de una manera que los demás no experimentan: sientes los estados emocionales del entorno como si fueran propios y tienes acceso a capas de realidad que escapan a lo racional. Esa sensibilidad es tu brújula más verdadera, aunque a veces también es la razón por la que te pierdes a ti mismo entre los demás."
};

window._SINT_LUNA = {
  aries:
    "Por dentro, el mundo emocional funciona de manera inmediata y sin filtro: sientes fuerte, reaccionas rápido y necesitas que lo que sientes tenga salida. La quietud emocional pesa; el movimiento, aunque sea inquieto, alivia. Aprender a hacer pausa antes de reaccionar es una de las claves de tu equilibrio interior.",
  tauro:
    "Por dentro, la estabilidad es la condición para funcionar: las emociones se asientan lento pero son profundas, y una vez que algo o alguien forma parte de tu mundo interior, lo cuidas con una fidelidad que no se negocia fácilmente. El cambio emocional brusco desestabiliza, y eso es una señal —no una debilidad.",
  geminis:
    "Por dentro, el mundo emocional funciona a través de las palabras: necesitas hablar lo que sientes, nombrarlo, darle forma intelectual. Sin esa traducción, las emociones generan ansiedad en lugar de orientación. Compartir lo que piensas es la manera más honesta que tienes de conectar con los demás.",
  cancer:
    "Por dentro, la intuición es casi sobrenatural y la memoria emocional guarda todo con una fidelidad impresionante. Necesitas vínculos donde puedas ser vulnerable sin que eso te cueste caro. Cuando te sientes seguro, tu mundo interior se convierte en un lugar de una profundidad extraordinaria.",
  leo:
    "Por dentro, la necesidad de sentirte especial para quienes amas es genuina y profunda. Las emociones son intensas, generosas, expresivas —y cuando te sientes reconocido, todo lo interior se convierte en un lugar muy cálido. El dolor más difícil suele llegar cuando esa reciprocidad no aparece.",
  virgo:
    "Por dentro, procesas lo que sientes con análisis: antes de permitirte una emoción completa, la mente ya la está examinando. Eso da claridad pero a veces aleja de la experiencia directa de sentir. El aprendizaje emocional más importante está en aprender a estar con lo que se siente, antes de entenderlo.",
  libra:
    "Por dentro, la paz relacional es la condición para estar bien: el conflicto no resuelto pesa de una manera que los demás no siempre entienden, y el mundo emocional florece en contextos de conexión genuina y armonía sostenida. El reto es aprender a defender lo que necesitas sin sentir que rompes algo.",
  escorpio:
    "Por dentro, las emociones no tienen zona intermedia: sientes todo con una intensidad que puede ser abrumadora, y hay una capacidad para la lealtad —y para el dolor— que pocos alcanzan esa profundidad. Aprender a soltar lo que ya cumplió su ciclo es el trabajo emocional más liberador que puedes hacer.",
  sagitario:
    "Por dentro, las emociones necesitan espacio y sentido: la sensación de estar atrapado emocionalmente no se tolera bien, y el mundo interior se expande cuando hay libertad, aprendizaje y algo en qué creer. La vulnerabilidad es real aunque cueste mostrarla —y admitirla es un acto de valentía propio.",
  capricornio:
    "Por dentro, guardas más de lo que muestras: las emociones son reales y profundas pero las administras con cuidado, y necesitas tiempo y confianza antes de permitir que alguien entre a tu mundo interior. Cuando esa confianza existe, eres de los vínculos más sólidos y serios que alguien puede tener.",
  acuario:
    "Por dentro, las emociones pasan por el filtro de la razón: sientes de una manera que no siempre se parece a lo que el mundo espera, y necesitas vínculos que respeten la independencia emocional. La soledad no asusta —lo que sí puede costar es admitir que la conexión también importa.",
  piscis:
    "Por dentro, las emociones no tienen bordes claros: absorbes los estados de quienes te rodean, sueñas despierto con facilidad y necesitas momentos de retiro para saber qué es tuyo y qué pertenece al mundo exterior. Ese espacio de silencio no es escape —es donde te encuentras a ti mismo."
};

window._SINT_ASC = {
  aries:
    "Hacia afuera, proyectas energía, iniciativa y una presencia que dice «ya voy» antes de que abras la boca. El mundo te ve como alguien directo y decidido, y esa imagen puede abrirte puertas antes incluso de que demuestres lo que sabes. El desafío es que a veces llega antes que tu intención real.",
  tauro:
    "Hacia afuera, proyectas una calma que tranquiliza y una presencia sólida que hace que la gente sienta que puede apoyarse en ti. El mundo te ve como alguien confiable y sereno, y esa imagen es real, aunque a veces subestiman la profundidad que hay detrás de esa superficie tranquila.",
  geminis:
    "Hacia afuera, proyectas curiosidad, humor y una facilidad para conectar que hace que los demás se sientan cómodos rápidamente. El mundo te ve como alguien ágil y sociable, y esa liviandad aparente esconde mucho más de lo que sueles mostrar en el primer encuentro.",
  cancer:
    "Hacia afuera, proyectas sensibilidad y cuidado, y la gente suele sentir que puede acercarse sin miedo. El mundo te ve como alguien cercano y cálido, y esa imagen te conecta profundamente con los demás —aunque también atrae a quienes necesitan más de lo que puedes dar.",
  leo:
    "Hacia afuera, proyectas una energía que ocupa el espacio de manera natural, y la gente suele notarte antes de que hagas algo especial para llamar la atención. El mundo te ve como alguien magnético y presente, y esa presencia no es actuada —es simplemente cómo llegas a los lugares.",
  virgo:
    "Hacia afuera, proyectas atención al detalle y una seriedad que genera confianza. El mundo te ve como alguien competente y organizado, y esa imagen hace que te encarguen más de lo que corresponde —porque pareces siempre capaz de manejar todo. Aprender a pedir ayuda también es parte del camino.",
  libra:
    "Hacia afuera, proyectas elegancia relacional y una facilidad para hacer sentir bien a los demás. El mundo te ve como alguien agradable y equilibrado, y esa imagen es genuina —aunque a veces cuesta que te tomen en serio cuando impones límites, porque nadie espera que alguien tan amable diga que no.",
  escorpio:
    "Hacia afuera, proyectas una profundidad que atrae y a la vez genera cierta cautela. El mundo te ve como alguien intenso y difícil de descifrar, y la gente siente que hay mucho más detrás de lo que muestras. En general tienen razón —y esa misteriosidad es parte de tu presencia, no un defecto.",
  sagitario:
    "Hacia afuera, proyectas entusiasmo, apertura y una energía que invita a moverse y a pensar en grande. El mundo te ve como alguien libre y expansivo, y esa imagen inspira a los demás —aunque a veces genera expectativas de disponibilidad que no siempre puedes sostener.",
  capricornio:
    "Hacia afuera, proyectas responsabilidad y una madurez que hace que confíen en ti incluso antes de conocerte bien. El mundo te ve como alguien serio y capaz, y esa imagen te abre puertas —aunque puede hacer que la gente olvide que también necesitas apoyo, no solo que piden el tuyo.",
  acuario:
    "Hacia afuera, proyectas una energía que no encaja fácilmente en ninguna categoría, y eso genera fascinación en algunos e incomodidad en otros. El mundo te ve como alguien original e impredecible, y tu presencia siempre deja huella —aunque no siempre del modo que esperabas.",
  piscis:
    "Hacia afuera, proyectas una energía fluida que se adapta al contexto, y la gente suele sentir que eres fácil de estar. El mundo te ve como alguien suave y difícil de definir, y aunque esa presencia conecta profundamente, rara vez llegan a conocerte del todo —porque hay capas que solo tú puedes ver."
};